/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the PublishPointHTTP type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublishPointHTTP{}

// PublishPointHTTP struct for PublishPointHTTP
type PublishPointHTTP struct {
	BasicAuth *PublishPointHTTPBasicAuth `json:"basic_auth,omitempty"`
	// Configures whether or not (and how) to compress manifests being published to the origin. If not specified, manifests will not be compressed.
	Compression interface{} `json:"compression,omitempty" enum:"NONE,GZIP" doc:"Configures whether or not (and how) to compress manifests being published to the origin. If not specified, manifests will not be compressed."`
	// (Optional) Specifies if this pubpoint should not be monitored by PLM.
	DoNotMonitor interface{} `json:"do_not_monitor,omitempty" doc:"(Optional) Specifies if this pubpoint should not be monitored by PLM."`
	// Allows custom HTTP headers to be set via configuration for all HTTP requests.
	Headers map[string]interface{} `json:"headers,omitempty" doc:"Allows custom HTTP headers to be set via configuration for all HTTP requests."`
	// Method overrides what HTTP method to specify in requests to the Publish Point. If not specified the service will default to POST.
	Method interface{} `json:"method,omitempty" doc:"Method overrides what HTTP method to specify in requests to the Publish Point. If not specified the service will default to POST."`
	// The base URL where published playlists will be able to be obtained. This is often different than the publish_base_url for CDN publishing workflows.
	PlaybackBaseUrl interface{} `json:"playback_base_url,omitempty" format:"uri-reference" doc:"The base URL where published playlists will be able to be obtained. This is often different than the publish_base_url for CDN publishing workflows."`
	// Specifies any query parameters that will be added to playback urls. Should not include the initial '?' Example: 'foo=bar&q=golang'
	PlaybackQueryParams interface{} `json:"playback_query_params,omitempty" doc:"Specifies any query parameters that will be added to playback urls. Should not include the initial '?' Example: 'foo=bar&q=golang'"`
	// The base URL where generated playlists will be sent/published. Each publish point requires a unique 'publish_base_url'.
	PublishBaseUrl interface{} `json:"publish_base_url,omitempty" format:"uri-reference" doc:"The base URL where generated playlists will be sent/published. Each publish point requires a unique 'publish_base_url'."`
	SecureHeaderAuth *PublishPointHTTPSecureHeaderAuth `json:"secure_header_auth,omitempty"`
}

// NewPublishPointHTTP instantiates a new PublishPointHTTP object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublishPointHTTP() *PublishPointHTTP {
	this := PublishPointHTTP{}
	return &this
}

// NewPublishPointHTTPWithDefaults instantiates a new PublishPointHTTP object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublishPointHTTPWithDefaults() *PublishPointHTTP {
	this := PublishPointHTTP{}
	return &this
}

// GetBasicAuth returns the BasicAuth field value if set, zero value otherwise.
func (o *PublishPointHTTP) GetBasicAuth() PublishPointHTTPBasicAuth {
	if o == nil || IsNil(o.BasicAuth) {
		var ret PublishPointHTTPBasicAuth
		return ret
	}
	return *o.BasicAuth
}

// GetBasicAuthOk returns a tuple with the BasicAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishPointHTTP) GetBasicAuthOk() (*PublishPointHTTPBasicAuth, bool) {
	if o == nil || IsNil(o.BasicAuth) {
		return nil, false
	}
	return o.BasicAuth, true
}

// HasBasicAuth returns a boolean if a field has been set.
func (o *PublishPointHTTP) HasBasicAuth() bool {
	if o != nil && !IsNil(o.BasicAuth) {
		return true
	}

	return false
}

// SetBasicAuth gets a reference to the given PublishPointHTTPBasicAuth and assigns it to the BasicAuth field.
func (o *PublishPointHTTP) SetBasicAuth(v PublishPointHTTPBasicAuth) {
	o.BasicAuth = &v
}

// GetCompression returns the Compression field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublishPointHTTP) GetCompression() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Compression
}

// GetCompressionOk returns a tuple with the Compression field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublishPointHTTP) GetCompressionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Compression) {
		return nil, false
	}
	return &o.Compression, true
}

// HasCompression returns a boolean if a field has been set.
func (o *PublishPointHTTP) HasCompression() bool {
	if o != nil && IsNil(o.Compression) {
		return true
	}

	return false
}

// SetCompression gets a reference to the given interface{} and assigns it to the Compression field.
func (o *PublishPointHTTP) SetCompression(v interface{}) {
	o.Compression = v
}

// GetDoNotMonitor returns the DoNotMonitor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublishPointHTTP) GetDoNotMonitor() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.DoNotMonitor
}

// GetDoNotMonitorOk returns a tuple with the DoNotMonitor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublishPointHTTP) GetDoNotMonitorOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DoNotMonitor) {
		return nil, false
	}
	return &o.DoNotMonitor, true
}

// HasDoNotMonitor returns a boolean if a field has been set.
func (o *PublishPointHTTP) HasDoNotMonitor() bool {
	if o != nil && IsNil(o.DoNotMonitor) {
		return true
	}

	return false
}

// SetDoNotMonitor gets a reference to the given interface{} and assigns it to the DoNotMonitor field.
func (o *PublishPointHTTP) SetDoNotMonitor(v interface{}) {
	o.DoNotMonitor = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublishPointHTTP) GetHeaders() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublishPointHTTP) GetHeadersOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return &o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *PublishPointHTTP) HasHeaders() bool {
	if o != nil && IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]interface{} and assigns it to the Headers field.
func (o *PublishPointHTTP) SetHeaders(v map[string]interface{}) {
	o.Headers = v
}

// GetMethod returns the Method field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublishPointHTTP) GetMethod() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublishPointHTTP) GetMethodOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return &o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *PublishPointHTTP) HasMethod() bool {
	if o != nil && IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given interface{} and assigns it to the Method field.
func (o *PublishPointHTTP) SetMethod(v interface{}) {
	o.Method = v
}

// GetPlaybackBaseUrl returns the PlaybackBaseUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublishPointHTTP) GetPlaybackBaseUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PlaybackBaseUrl
}

// GetPlaybackBaseUrlOk returns a tuple with the PlaybackBaseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublishPointHTTP) GetPlaybackBaseUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PlaybackBaseUrl) {
		return nil, false
	}
	return &o.PlaybackBaseUrl, true
}

// HasPlaybackBaseUrl returns a boolean if a field has been set.
func (o *PublishPointHTTP) HasPlaybackBaseUrl() bool {
	if o != nil && IsNil(o.PlaybackBaseUrl) {
		return true
	}

	return false
}

// SetPlaybackBaseUrl gets a reference to the given interface{} and assigns it to the PlaybackBaseUrl field.
func (o *PublishPointHTTP) SetPlaybackBaseUrl(v interface{}) {
	o.PlaybackBaseUrl = v
}

// GetPlaybackQueryParams returns the PlaybackQueryParams field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublishPointHTTP) GetPlaybackQueryParams() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PlaybackQueryParams
}

// GetPlaybackQueryParamsOk returns a tuple with the PlaybackQueryParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublishPointHTTP) GetPlaybackQueryParamsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PlaybackQueryParams) {
		return nil, false
	}
	return &o.PlaybackQueryParams, true
}

// HasPlaybackQueryParams returns a boolean if a field has been set.
func (o *PublishPointHTTP) HasPlaybackQueryParams() bool {
	if o != nil && IsNil(o.PlaybackQueryParams) {
		return true
	}

	return false
}

// SetPlaybackQueryParams gets a reference to the given interface{} and assigns it to the PlaybackQueryParams field.
func (o *PublishPointHTTP) SetPlaybackQueryParams(v interface{}) {
	o.PlaybackQueryParams = v
}

// GetPublishBaseUrl returns the PublishBaseUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublishPointHTTP) GetPublishBaseUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PublishBaseUrl
}

// GetPublishBaseUrlOk returns a tuple with the PublishBaseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublishPointHTTP) GetPublishBaseUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PublishBaseUrl) {
		return nil, false
	}
	return &o.PublishBaseUrl, true
}

// HasPublishBaseUrl returns a boolean if a field has been set.
func (o *PublishPointHTTP) HasPublishBaseUrl() bool {
	if o != nil && IsNil(o.PublishBaseUrl) {
		return true
	}

	return false
}

// SetPublishBaseUrl gets a reference to the given interface{} and assigns it to the PublishBaseUrl field.
func (o *PublishPointHTTP) SetPublishBaseUrl(v interface{}) {
	o.PublishBaseUrl = v
}

// GetSecureHeaderAuth returns the SecureHeaderAuth field value if set, zero value otherwise.
func (o *PublishPointHTTP) GetSecureHeaderAuth() PublishPointHTTPSecureHeaderAuth {
	if o == nil || IsNil(o.SecureHeaderAuth) {
		var ret PublishPointHTTPSecureHeaderAuth
		return ret
	}
	return *o.SecureHeaderAuth
}

// GetSecureHeaderAuthOk returns a tuple with the SecureHeaderAuth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublishPointHTTP) GetSecureHeaderAuthOk() (*PublishPointHTTPSecureHeaderAuth, bool) {
	if o == nil || IsNil(o.SecureHeaderAuth) {
		return nil, false
	}
	return o.SecureHeaderAuth, true
}

// HasSecureHeaderAuth returns a boolean if a field has been set.
func (o *PublishPointHTTP) HasSecureHeaderAuth() bool {
	if o != nil && !IsNil(o.SecureHeaderAuth) {
		return true
	}

	return false
}

// SetSecureHeaderAuth gets a reference to the given PublishPointHTTPSecureHeaderAuth and assigns it to the SecureHeaderAuth field.
func (o *PublishPointHTTP) SetSecureHeaderAuth(v PublishPointHTTPSecureHeaderAuth) {
	o.SecureHeaderAuth = &v
}

func (o PublishPointHTTP) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublishPointHTTP) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BasicAuth) {
		toSerialize["basic_auth"] = o.BasicAuth
	}
	if o.Compression != nil {
		toSerialize["compression"] = o.Compression
	}
	if o.DoNotMonitor != nil {
		toSerialize["do_not_monitor"] = o.DoNotMonitor
	}
	if o.Headers != nil {
		toSerialize["headers"] = o.Headers
	}
	if o.Method != nil {
		toSerialize["method"] = o.Method
	}
	if o.PlaybackBaseUrl != nil {
		toSerialize["playback_base_url"] = o.PlaybackBaseUrl
	}
	if o.PlaybackQueryParams != nil {
		toSerialize["playback_query_params"] = o.PlaybackQueryParams
	}
	if o.PublishBaseUrl != nil {
		toSerialize["publish_base_url"] = o.PublishBaseUrl
	}
	if !IsNil(o.SecureHeaderAuth) {
		toSerialize["secure_header_auth"] = o.SecureHeaderAuth
	}
	return toSerialize, nil
}

type NullablePublishPointHTTP struct {
	value *PublishPointHTTP
	isSet bool
}

func (v NullablePublishPointHTTP) Get() *PublishPointHTTP {
	return v.value
}

func (v *NullablePublishPointHTTP) Set(val *PublishPointHTTP) {
	v.value = val
	v.isSet = true
}

func (v NullablePublishPointHTTP) IsSet() bool {
	return v.isSet
}

func (v *NullablePublishPointHTTP) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublishPointHTTP(val *PublishPointHTTP) *NullablePublishPointHTTP {
	return &NullablePublishPointHTTP{value: val, isSet: true}
}

func (v NullablePublishPointHTTP) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublishPointHTTP) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


