/*
 * iStreamPlanet Channels API
 *
 * API version: 0.0.0
 * Contact: support@istreamplanet.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// ChannelPackagingPackagersValueMp4 Uses MP4 format for each segments. Only one of ['mp2t', 'mp4'] may be set.
type ChannelPackagingPackagersValueMp4 struct {
	// CaptionPlacement defines where caption messages should be placed in the output MP4.
	CaptionPlacement *string `json:"caption_placement,omitempty"`
	// Insert pssh boxes generated by content protection into packaged segments. Defaults to not insert pssh boxes to the packaged segments.
	InsertPsshBox *bool `json:"insert_pssh_box,omitempty"`
}

// NewChannelPackagingPackagersValueMp4 instantiates a new ChannelPackagingPackagersValueMp4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelPackagingPackagersValueMp4() *ChannelPackagingPackagersValueMp4 {
	this := ChannelPackagingPackagersValueMp4{}
	return &this
}

// NewChannelPackagingPackagersValueMp4WithDefaults instantiates a new ChannelPackagingPackagersValueMp4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelPackagingPackagersValueMp4WithDefaults() *ChannelPackagingPackagersValueMp4 {
	this := ChannelPackagingPackagersValueMp4{}
	return &this
}

// GetCaptionPlacement returns the CaptionPlacement field value if set, zero value otherwise.
func (o *ChannelPackagingPackagersValueMp4) GetCaptionPlacement() string {
	if o == nil || o.CaptionPlacement == nil {
		var ret string
		return ret
	}
	return *o.CaptionPlacement
}

// GetCaptionPlacementOk returns a tuple with the CaptionPlacement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelPackagingPackagersValueMp4) GetCaptionPlacementOk() (*string, bool) {
	if o == nil || o.CaptionPlacement == nil {
		return nil, false
	}
	return o.CaptionPlacement, true
}

// HasCaptionPlacement returns a boolean if a field has been set.
func (o *ChannelPackagingPackagersValueMp4) HasCaptionPlacement() bool {
	if o != nil && o.CaptionPlacement != nil {
		return true
	}

	return false
}

// SetCaptionPlacement gets a reference to the given string and assigns it to the CaptionPlacement field.
func (o *ChannelPackagingPackagersValueMp4) SetCaptionPlacement(v string) {
	o.CaptionPlacement = &v
}

// GetInsertPsshBox returns the InsertPsshBox field value if set, zero value otherwise.
func (o *ChannelPackagingPackagersValueMp4) GetInsertPsshBox() bool {
	if o == nil || o.InsertPsshBox == nil {
		var ret bool
		return ret
	}
	return *o.InsertPsshBox
}

// GetInsertPsshBoxOk returns a tuple with the InsertPsshBox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelPackagingPackagersValueMp4) GetInsertPsshBoxOk() (*bool, bool) {
	if o == nil || o.InsertPsshBox == nil {
		return nil, false
	}
	return o.InsertPsshBox, true
}

// HasInsertPsshBox returns a boolean if a field has been set.
func (o *ChannelPackagingPackagersValueMp4) HasInsertPsshBox() bool {
	if o != nil && o.InsertPsshBox != nil {
		return true
	}

	return false
}

// SetInsertPsshBox gets a reference to the given bool and assigns it to the InsertPsshBox field.
func (o *ChannelPackagingPackagersValueMp4) SetInsertPsshBox(v bool) {
	o.InsertPsshBox = &v
}

func (o ChannelPackagingPackagersValueMp4) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CaptionPlacement != nil {
		toSerialize["caption_placement"] = o.CaptionPlacement
	}
	if o.InsertPsshBox != nil {
		toSerialize["insert_pssh_box"] = o.InsertPsshBox
	}
	return json.Marshal(toSerialize)
}

type NullableChannelPackagingPackagersValueMp4 struct {
	value *ChannelPackagingPackagersValueMp4
	isSet bool
}

func (v NullableChannelPackagingPackagersValueMp4) Get() *ChannelPackagingPackagersValueMp4 {
	return v.value
}

func (v *NullableChannelPackagingPackagersValueMp4) Set(val *ChannelPackagingPackagersValueMp4) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelPackagingPackagersValueMp4) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelPackagingPackagersValueMp4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelPackagingPackagersValueMp4(val *ChannelPackagingPackagersValueMp4) *NullableChannelPackagingPackagersValueMp4 {
	return &NullableChannelPackagingPackagersValueMp4{value: val, isSet: true}
}

func (v NullableChannelPackagingPackagersValueMp4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelPackagingPackagersValueMp4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


