/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter{}

// PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter struct for PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter
type PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter struct {
	ExplicitTier *PutChannelRequestBodySignalingSegmentSettingsInnerTierFilterExplicitTier `json:"explicit_tier,omitempty"`
}

// NewPutChannelRequestBodySignalingSegmentSettingsInnerTierFilter instantiates a new PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutChannelRequestBodySignalingSegmentSettingsInnerTierFilter() *PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter {
	this := PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter{}
	return &this
}

// NewPutChannelRequestBodySignalingSegmentSettingsInnerTierFilterWithDefaults instantiates a new PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutChannelRequestBodySignalingSegmentSettingsInnerTierFilterWithDefaults() *PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter {
	this := PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter{}
	return &this
}

// GetExplicitTier returns the ExplicitTier field value if set, zero value otherwise.
func (o *PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) GetExplicitTier() PutChannelRequestBodySignalingSegmentSettingsInnerTierFilterExplicitTier {
	if o == nil || IsNil(o.ExplicitTier) {
		var ret PutChannelRequestBodySignalingSegmentSettingsInnerTierFilterExplicitTier
		return ret
	}
	return *o.ExplicitTier
}

// GetExplicitTierOk returns a tuple with the ExplicitTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) GetExplicitTierOk() (*PutChannelRequestBodySignalingSegmentSettingsInnerTierFilterExplicitTier, bool) {
	if o == nil || IsNil(o.ExplicitTier) {
		return nil, false
	}
	return o.ExplicitTier, true
}

// HasExplicitTier returns a boolean if a field has been set.
func (o *PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) HasExplicitTier() bool {
	if o != nil && !IsNil(o.ExplicitTier) {
		return true
	}

	return false
}

// SetExplicitTier gets a reference to the given PutChannelRequestBodySignalingSegmentSettingsInnerTierFilterExplicitTier and assigns it to the ExplicitTier field.
func (o *PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) SetExplicitTier(v PutChannelRequestBodySignalingSegmentSettingsInnerTierFilterExplicitTier) {
	o.ExplicitTier = &v
}

func (o PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExplicitTier) {
		toSerialize["explicit_tier"] = o.ExplicitTier
	}
	return toSerialize, nil
}

type NullablePutChannelRequestBodySignalingSegmentSettingsInnerTierFilter struct {
	value *PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter
	isSet bool
}

func (v NullablePutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) Get() *PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter {
	return v.value
}

func (v *NullablePutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) Set(val *PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) {
	v.value = val
	v.isSet = true
}

func (v NullablePutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) IsSet() bool {
	return v.isSet
}

func (v *NullablePutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutChannelRequestBodySignalingSegmentSettingsInnerTierFilter(val *PutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) *NullablePutChannelRequestBodySignalingSegmentSettingsInnerTierFilter {
	return &NullablePutChannelRequestBodySignalingSegmentSettingsInnerTierFilter{value: val, isSet: true}
}

func (v NullablePutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutChannelRequestBodySignalingSegmentSettingsInnerTierFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
