/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
	"time"
)

// checks if the ListContentSegmentHistoryResponseContentSegmentsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListContentSegmentHistoryResponseContentSegmentsInner{}

// ListContentSegmentHistoryResponseContentSegmentsInner struct for ListContentSegmentHistoryResponseContentSegmentsInner
type ListContentSegmentHistoryResponseContentSegmentsInner struct {
	// end is the timestamp when the content segment ended.
	End *time.Time `json:"end,omitempty" format:"date-time" doc:"end is the timestamp when the content segment ended."`
	// segment_id is a unique id assigned by the transcoder
	SegmentId *int32 `json:"segment_id,omitempty" format:"int32" minimum:"0" doc:"segment_id is a unique id assigned by the transcoder"`
	// signal_source denotes whether the content segment was initiated by an in-band signaling event or an out-of-band signaling event where in-band signals are received in the source consumed by the transcoder.
	SignalSource *string `json:"signal_source,omitempty" enum:"SIGNAL_SOURCE_UNDEFINED,SIGNAL_SOURCE_IN_BAND,SIGNAL_SOURCE_OUT_OF_BAND" doc:"signal_source denotes whether the content segment was initiated by an in-band signaling event or an out-of-band signaling event where in-band signals are received in the source consumed by the transcoder."`
	// start is the timestamp when the content segment started.
	Start *time.Time `json:"start,omitempty" format:"date-time" doc:"start is the timestamp when the content segment started."`
	// The type of content segment. Currently only supports PROGRAM, CHAPTER, or BREAK.
	Type *string `json:"type,omitempty" enum:"SPLICE_INSERT,CONTENT_ID,PROGRAM,PROGRAM_BLACKOUT_OVERRIDE,PROGRAM_BREAKAWAY,CHAPTER,BREAK,OPENING_CREDIT,CLOSING_CREDIT,PROVIDER_PLACEMENT_OP,DISTRIBUTOR_PLACEMENT_OP,PROVIDER_OVERLAY_OP,DISTRIBUTOR_OVERLAY_OP,PROVIDER_AD,DISTRIBUTOR_AD,UNSCHEDULED_EVENT,NETWORK,SLATE,NOT_INDICATED,TIMED_METADATA,TIMED_METADATA_MARKER_OVER_SLATE" doc:"The type of content segment. Currently only supports PROGRAM, CHAPTER, or BREAK."`
	Upids []ListContentSegmentHistoryResponseContentSegmentsInnerUpidsInner `json:"upids,omitempty"`
}

// NewListContentSegmentHistoryResponseContentSegmentsInner instantiates a new ListContentSegmentHistoryResponseContentSegmentsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListContentSegmentHistoryResponseContentSegmentsInner() *ListContentSegmentHistoryResponseContentSegmentsInner {
	this := ListContentSegmentHistoryResponseContentSegmentsInner{}
	return &this
}

// NewListContentSegmentHistoryResponseContentSegmentsInnerWithDefaults instantiates a new ListContentSegmentHistoryResponseContentSegmentsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListContentSegmentHistoryResponseContentSegmentsInnerWithDefaults() *ListContentSegmentHistoryResponseContentSegmentsInner {
	this := ListContentSegmentHistoryResponseContentSegmentsInner{}
	return &this
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) GetEnd() time.Time {
	if o == nil || IsNil(o.End) {
		var ret time.Time
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) GetEndOk() (*time.Time, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given time.Time and assigns it to the End field.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) SetEnd(v time.Time) {
	o.End = &v
}

// GetSegmentId returns the SegmentId field value if set, zero value otherwise.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) GetSegmentId() int32 {
	if o == nil || IsNil(o.SegmentId) {
		var ret int32
		return ret
	}
	return *o.SegmentId
}

// GetSegmentIdOk returns a tuple with the SegmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) GetSegmentIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SegmentId) {
		return nil, false
	}
	return o.SegmentId, true
}

// HasSegmentId returns a boolean if a field has been set.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) HasSegmentId() bool {
	if o != nil && !IsNil(o.SegmentId) {
		return true
	}

	return false
}

// SetSegmentId gets a reference to the given int32 and assigns it to the SegmentId field.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) SetSegmentId(v int32) {
	o.SegmentId = &v
}

// GetSignalSource returns the SignalSource field value if set, zero value otherwise.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) GetSignalSource() string {
	if o == nil || IsNil(o.SignalSource) {
		var ret string
		return ret
	}
	return *o.SignalSource
}

// GetSignalSourceOk returns a tuple with the SignalSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) GetSignalSourceOk() (*string, bool) {
	if o == nil || IsNil(o.SignalSource) {
		return nil, false
	}
	return o.SignalSource, true
}

// HasSignalSource returns a boolean if a field has been set.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) HasSignalSource() bool {
	if o != nil && !IsNil(o.SignalSource) {
		return true
	}

	return false
}

// SetSignalSource gets a reference to the given string and assigns it to the SignalSource field.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) SetSignalSource(v string) {
	o.SignalSource = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) GetStart() time.Time {
	if o == nil || IsNil(o.Start) {
		var ret time.Time
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) GetStartOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Start) {
		return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) HasStart() bool {
	if o != nil && !IsNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given time.Time and assigns it to the Start field.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) SetStart(v time.Time) {
	o.Start = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) SetType(v string) {
	o.Type = &v
}

// GetUpids returns the Upids field value if set, zero value otherwise.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) GetUpids() []ListContentSegmentHistoryResponseContentSegmentsInnerUpidsInner {
	if o == nil || IsNil(o.Upids) {
		var ret []ListContentSegmentHistoryResponseContentSegmentsInnerUpidsInner
		return ret
	}
	return o.Upids
}

// GetUpidsOk returns a tuple with the Upids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) GetUpidsOk() ([]ListContentSegmentHistoryResponseContentSegmentsInnerUpidsInner, bool) {
	if o == nil || IsNil(o.Upids) {
		return nil, false
	}
	return o.Upids, true
}

// HasUpids returns a boolean if a field has been set.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) HasUpids() bool {
	if o != nil && !IsNil(o.Upids) {
		return true
	}

	return false
}

// SetUpids gets a reference to the given []ListContentSegmentHistoryResponseContentSegmentsInnerUpidsInner and assigns it to the Upids field.
func (o *ListContentSegmentHistoryResponseContentSegmentsInner) SetUpids(v []ListContentSegmentHistoryResponseContentSegmentsInnerUpidsInner) {
	o.Upids = v
}

func (o ListContentSegmentHistoryResponseContentSegmentsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListContentSegmentHistoryResponseContentSegmentsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	if !IsNil(o.SegmentId) {
		toSerialize["segment_id"] = o.SegmentId
	}
	if !IsNil(o.SignalSource) {
		toSerialize["signal_source"] = o.SignalSource
	}
	if !IsNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Upids) {
		toSerialize["upids"] = o.Upids
	}
	return toSerialize, nil
}

type NullableListContentSegmentHistoryResponseContentSegmentsInner struct {
	value *ListContentSegmentHistoryResponseContentSegmentsInner
	isSet bool
}

func (v NullableListContentSegmentHistoryResponseContentSegmentsInner) Get() *ListContentSegmentHistoryResponseContentSegmentsInner {
	return v.value
}

func (v *NullableListContentSegmentHistoryResponseContentSegmentsInner) Set(val *ListContentSegmentHistoryResponseContentSegmentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListContentSegmentHistoryResponseContentSegmentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListContentSegmentHistoryResponseContentSegmentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListContentSegmentHistoryResponseContentSegmentsInner(val *ListContentSegmentHistoryResponseContentSegmentsInner) *NullableListContentSegmentHistoryResponseContentSegmentsInner {
	return &NullableListContentSegmentHistoryResponseContentSegmentsInner{value: val, isSet: true}
}

func (v NullableListContentSegmentHistoryResponseContentSegmentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListContentSegmentHistoryResponseContentSegmentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


