/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the CollapseVODResponseBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CollapseVODResponseBody{}

// CollapseVODResponseBody struct for CollapseVODResponseBody
type CollapseVODResponseBody struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" format:"uri" doc:"A URL to the JSON Schema for this object."`
	// New Clip ID for collapsed vod
	ClipId int64 `json:"clip_id" format:"int64" doc:"New Clip ID for collapsed vod"`
	// Identifies collapse task id
	TaskId string `json:"task_id" doc:"Identifies collapse task id"`
}

// NewCollapseVODResponseBody instantiates a new CollapseVODResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollapseVODResponseBody(clipId int64, taskId string) *CollapseVODResponseBody {
	this := CollapseVODResponseBody{}
	this.ClipId = clipId
	this.TaskId = taskId
	return &this
}

// NewCollapseVODResponseBodyWithDefaults instantiates a new CollapseVODResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollapseVODResponseBodyWithDefaults() *CollapseVODResponseBody {
	this := CollapseVODResponseBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *CollapseVODResponseBody) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollapseVODResponseBody) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *CollapseVODResponseBody) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *CollapseVODResponseBody) SetSchema(v string) {
	o.Schema = &v
}

// GetClipId returns the ClipId field value
func (o *CollapseVODResponseBody) GetClipId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ClipId
}

// GetClipIdOk returns a tuple with the ClipId field value
// and a boolean to check if the value has been set.
func (o *CollapseVODResponseBody) GetClipIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClipId, true
}

// SetClipId sets field value
func (o *CollapseVODResponseBody) SetClipId(v int64) {
	o.ClipId = v
}

// GetTaskId returns the TaskId field value
func (o *CollapseVODResponseBody) GetTaskId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value
// and a boolean to check if the value has been set.
func (o *CollapseVODResponseBody) GetTaskIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TaskId, true
}

// SetTaskId sets field value
func (o *CollapseVODResponseBody) SetTaskId(v string) {
	o.TaskId = v
}

func (o CollapseVODResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CollapseVODResponseBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["clip_id"] = o.ClipId
	toSerialize["task_id"] = o.TaskId
	return toSerialize, nil
}

type NullableCollapseVODResponseBody struct {
	value *CollapseVODResponseBody
	isSet bool
}

func (v NullableCollapseVODResponseBody) Get() *CollapseVODResponseBody {
	return v.value
}

func (v *NullableCollapseVODResponseBody) Set(val *CollapseVODResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCollapseVODResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCollapseVODResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollapseVODResponseBody(val *CollapseVODResponseBody) *NullableCollapseVODResponseBody {
	return &NullableCollapseVODResponseBody{value: val, isSet: true}
}

func (v NullableCollapseVODResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollapseVODResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
