/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the PublicationStartoverOnAiringId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicationStartoverOnAiringId{}

// PublicationStartoverOnAiringId struct for PublicationStartoverOnAiringId
type PublicationStartoverOnAiringId struct {
	// Airing Id is a SCTE-35 Segmentation Unique Program ID (UPID) of type 0x08 used to specify the unique airing of a program. Is a 8 byte hex encoded string that is prepended with '0x'.
	AiringId interface{} `json:"airing_id,omitempty" pattern:"^0x[0-9a-fA-F]{16}$" doc:"Airing Id is a SCTE-35 Segmentation Unique Program ID (UPID) of type 0x08 used to specify the unique airing of a program. Is a 8 byte hex encoded string that is prepended with '0x'."`
}

// NewPublicationStartoverOnAiringId instantiates a new PublicationStartoverOnAiringId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicationStartoverOnAiringId() *PublicationStartoverOnAiringId {
	this := PublicationStartoverOnAiringId{}
	return &this
}

// NewPublicationStartoverOnAiringIdWithDefaults instantiates a new PublicationStartoverOnAiringId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicationStartoverOnAiringIdWithDefaults() *PublicationStartoverOnAiringId {
	this := PublicationStartoverOnAiringId{}
	return &this
}

// GetAiringId returns the AiringId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PublicationStartoverOnAiringId) GetAiringId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.AiringId
}

// GetAiringIdOk returns a tuple with the AiringId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PublicationStartoverOnAiringId) GetAiringIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.AiringId) {
		return nil, false
	}
	return &o.AiringId, true
}

// HasAiringId returns a boolean if a field has been set.
func (o *PublicationStartoverOnAiringId) HasAiringId() bool {
	if o != nil && IsNil(o.AiringId) {
		return true
	}

	return false
}

// SetAiringId gets a reference to the given interface{} and assigns it to the AiringId field.
func (o *PublicationStartoverOnAiringId) SetAiringId(v interface{}) {
	o.AiringId = v
}

func (o PublicationStartoverOnAiringId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicationStartoverOnAiringId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AiringId != nil {
		toSerialize["airing_id"] = o.AiringId
	}
	return toSerialize, nil
}

type NullablePublicationStartoverOnAiringId struct {
	value *PublicationStartoverOnAiringId
	isSet bool
}

func (v NullablePublicationStartoverOnAiringId) Get() *PublicationStartoverOnAiringId {
	return v.value
}

func (v *NullablePublicationStartoverOnAiringId) Set(val *PublicationStartoverOnAiringId) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicationStartoverOnAiringId) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicationStartoverOnAiringId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicationStartoverOnAiringId(val *PublicationStartoverOnAiringId) *NullablePublicationStartoverOnAiringId {
	return &NullablePublicationStartoverOnAiringId{value: val, isSet: true}
}

func (v NullablePublicationStartoverOnAiringId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicationStartoverOnAiringId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


