/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the ListProductsResponseBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListProductsResponseBody{}

// ListProductsResponseBody struct for ListProductsResponseBody
type ListProductsResponseBody struct {
	// A URL to the JSON Schema for this object.
	Schema interface{} `json:"$schema,omitempty" format:"uri" doc:"A URL to the JSON Schema for this object."`
	// Errors when fetching products
	Errors interface{} `json:"errors" doc:"Errors when fetching products"`
	// Product Array
	Products interface{} `json:"products" doc:"Product Array"`
}

// NewListProductsResponseBody instantiates a new ListProductsResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListProductsResponseBody(errors interface{}, products interface{}) *ListProductsResponseBody {
	this := ListProductsResponseBody{}
	this.Errors = errors
	this.Products = products
	return &this
}

// NewListProductsResponseBodyWithDefaults instantiates a new ListProductsResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListProductsResponseBodyWithDefaults() *ListProductsResponseBody {
	this := ListProductsResponseBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListProductsResponseBody) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListProductsResponseBody) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *ListProductsResponseBody) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *ListProductsResponseBody) SetSchema(v interface{}) {
	o.Schema = v
}

// GetErrors returns the Errors field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ListProductsResponseBody) GetErrors() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListProductsResponseBody) GetErrorsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return &o.Errors, true
}

// SetErrors sets field value
func (o *ListProductsResponseBody) SetErrors(v interface{}) {
	o.Errors = v
}

// GetProducts returns the Products field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ListProductsResponseBody) GetProducts() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Products
}

// GetProductsOk returns a tuple with the Products field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListProductsResponseBody) GetProductsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Products) {
		return nil, false
	}
	return &o.Products, true
}

// SetProducts sets field value
func (o *ListProductsResponseBody) SetProducts(v interface{}) {
	o.Products = v
}

func (o ListProductsResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListProductsResponseBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Schema != nil {
		toSerialize["$schema"] = o.Schema
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	if o.Products != nil {
		toSerialize["products"] = o.Products
	}
	return toSerialize, nil
}

type NullableListProductsResponseBody struct {
	value *ListProductsResponseBody
	isSet bool
}

func (v NullableListProductsResponseBody) Get() *ListProductsResponseBody {
	return v.value
}

func (v *NullableListProductsResponseBody) Set(val *ListProductsResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableListProductsResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableListProductsResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListProductsResponseBody(val *ListProductsResponseBody) *NullableListProductsResponseBody {
	return &NullableListProductsResponseBody{value: val, isSet: true}
}

func (v NullableListProductsResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListProductsResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


