/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81{}

// PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81 struct for PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81
type PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81 struct {
	Clli interface{} `json:"clli,omitempty"`
	// Configures custom Level 8 metadata. Each target may be configured at most once. Unconfigured targets use the Dolby LDP SIDK defaults.
	Level8 []PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81Level8Inner `json:"level8,omitempty" doc:"Configures custom Level 8 metadata. Each target may be configured at most once. Unconfigured targets use the Dolby LDP SIDK defaults."`
	Mdcv   interface{}                                                                               `json:"mdcv,omitempty"`
}

// NewPatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81 instantiates a new PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81() *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81 {
	this := PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81{}
	return &this
}

// NewPatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81WithDefaults instantiates a new PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81WithDefaults() *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81 {
	this := PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81{}
	return &this
}

// GetClli returns the Clli field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) GetClli() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Clli
}

// GetClliOk returns a tuple with the Clli field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) GetClliOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Clli) {
		return nil, false
	}
	return &o.Clli, true
}

// HasClli returns a boolean if a field has been set.
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) HasClli() bool {
	if o != nil && IsNil(o.Clli) {
		return true
	}

	return false
}

// SetClli gets a reference to the given interface{} and assigns it to the Clli field.
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) SetClli(v interface{}) {
	o.Clli = v
}

// GetLevel8 returns the Level8 field value if set, zero value otherwise.
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) GetLevel8() []PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81Level8Inner {
	if o == nil || IsNil(o.Level8) {
		var ret []PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81Level8Inner
		return ret
	}
	return o.Level8
}

// GetLevel8Ok returns a tuple with the Level8 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) GetLevel8Ok() ([]PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81Level8Inner, bool) {
	if o == nil || IsNil(o.Level8) {
		return nil, false
	}
	return o.Level8, true
}

// HasLevel8 returns a boolean if a field has been set.
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) HasLevel8() bool {
	if o != nil && !IsNil(o.Level8) {
		return true
	}

	return false
}

// SetLevel8 gets a reference to the given []PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81Level8Inner and assigns it to the Level8 field.
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) SetLevel8(v []PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81Level8Inner) {
	o.Level8 = v
}

// GetMdcv returns the Mdcv field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) GetMdcv() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Mdcv
}

// GetMdcvOk returns a tuple with the Mdcv field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) GetMdcvOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Mdcv) {
		return nil, false
	}
	return &o.Mdcv, true
}

// HasMdcv returns a boolean if a field has been set.
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) HasMdcv() bool {
	if o != nil && IsNil(o.Mdcv) {
		return true
	}

	return false
}

// SetMdcv gets a reference to the given interface{} and assigns it to the Mdcv field.
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) SetMdcv(v interface{}) {
	o.Mdcv = v
}

func (o PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Clli != nil {
		toSerialize["clli"] = o.Clli
	}
	if !IsNil(o.Level8) {
		toSerialize["level8"] = o.Level8
	}
	if o.Mdcv != nil {
		toSerialize["mdcv"] = o.Mdcv
	}
	return toSerialize, nil
}

type NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81 struct {
	value *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81
	isSet bool
}

func (v NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) Get() *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81 {
	return v.value
}

func (v *NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) Set(val *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81(val *PatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) *NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81 {
	return &NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81{value: val, isSet: true}
}

func (v NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerH265HdrDolbyVisionProfile81) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
