/*
 * iStreamPlanet Channels API
 *
 * API version: 0.0.0
 * Contact: support@istreamplanet.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// GetPreviewStreamsResponse struct for GetPreviewStreamsResponse
type GetPreviewStreamsResponse struct {
	// An optional URL to a JSON Schema document describing this resource
	Schema *string `json:"$schema,omitempty"`
	// Lists of all audio and video tracks that are available. Note: the default audio and video track info will also appear here.
	AudioTracks []GetPreviewStreamsResponseAudioTracksInner `json:"audio_tracks,omitempty"`
	DefaultAudioTrack *GetPreviewStreamsResponseDefaultAudioTrack `json:"default_audio_track,omitempty"`
	// default_url contains the default URL that can be used to start playback. Ex: https://example.com/cluster/org/isp/ext_id/foo/play?vid_id=2&aud_id=6 The vid_id and aud_id can be changed utilizing the ones provided by the 'audio_tracks' and 'video_tracks' fields to see different combinations.
	DefaultUrl *string `json:"default_url,omitempty"`
	DefaultVideoTrack *GetPreviewStreamsResponseDefaultVideoTrack `json:"default_video_track,omitempty"`
	// JWT Bearer token that shall be supplied with a 'pre-flight' to myriapod.js to send the auth token to the server.
	Token *string `json:"token,omitempty"`
	VideoTracks []GetPreviewStreamsResponseDefaultVideoTrack `json:"video_tracks,omitempty"`
}

// NewGetPreviewStreamsResponse instantiates a new GetPreviewStreamsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPreviewStreamsResponse() *GetPreviewStreamsResponse {
	this := GetPreviewStreamsResponse{}
	return &this
}

// NewGetPreviewStreamsResponseWithDefaults instantiates a new GetPreviewStreamsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPreviewStreamsResponseWithDefaults() *GetPreviewStreamsResponse {
	this := GetPreviewStreamsResponse{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponse) GetSchema() string {
	if o == nil || o.Schema == nil {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponse) GetSchemaOk() (*string, bool) {
	if o == nil || o.Schema == nil {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponse) HasSchema() bool {
	if o != nil && o.Schema != nil {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *GetPreviewStreamsResponse) SetSchema(v string) {
	o.Schema = &v
}

// GetAudioTracks returns the AudioTracks field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponse) GetAudioTracks() []GetPreviewStreamsResponseAudioTracksInner {
	if o == nil || o.AudioTracks == nil {
		var ret []GetPreviewStreamsResponseAudioTracksInner
		return ret
	}
	return o.AudioTracks
}

// GetAudioTracksOk returns a tuple with the AudioTracks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponse) GetAudioTracksOk() ([]GetPreviewStreamsResponseAudioTracksInner, bool) {
	if o == nil || o.AudioTracks == nil {
		return nil, false
	}
	return o.AudioTracks, true
}

// HasAudioTracks returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponse) HasAudioTracks() bool {
	if o != nil && o.AudioTracks != nil {
		return true
	}

	return false
}

// SetAudioTracks gets a reference to the given []GetPreviewStreamsResponseAudioTracksInner and assigns it to the AudioTracks field.
func (o *GetPreviewStreamsResponse) SetAudioTracks(v []GetPreviewStreamsResponseAudioTracksInner) {
	o.AudioTracks = v
}

// GetDefaultAudioTrack returns the DefaultAudioTrack field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponse) GetDefaultAudioTrack() GetPreviewStreamsResponseDefaultAudioTrack {
	if o == nil || o.DefaultAudioTrack == nil {
		var ret GetPreviewStreamsResponseDefaultAudioTrack
		return ret
	}
	return *o.DefaultAudioTrack
}

// GetDefaultAudioTrackOk returns a tuple with the DefaultAudioTrack field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponse) GetDefaultAudioTrackOk() (*GetPreviewStreamsResponseDefaultAudioTrack, bool) {
	if o == nil || o.DefaultAudioTrack == nil {
		return nil, false
	}
	return o.DefaultAudioTrack, true
}

// HasDefaultAudioTrack returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponse) HasDefaultAudioTrack() bool {
	if o != nil && o.DefaultAudioTrack != nil {
		return true
	}

	return false
}

// SetDefaultAudioTrack gets a reference to the given GetPreviewStreamsResponseDefaultAudioTrack and assigns it to the DefaultAudioTrack field.
func (o *GetPreviewStreamsResponse) SetDefaultAudioTrack(v GetPreviewStreamsResponseDefaultAudioTrack) {
	o.DefaultAudioTrack = &v
}

// GetDefaultUrl returns the DefaultUrl field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponse) GetDefaultUrl() string {
	if o == nil || o.DefaultUrl == nil {
		var ret string
		return ret
	}
	return *o.DefaultUrl
}

// GetDefaultUrlOk returns a tuple with the DefaultUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponse) GetDefaultUrlOk() (*string, bool) {
	if o == nil || o.DefaultUrl == nil {
		return nil, false
	}
	return o.DefaultUrl, true
}

// HasDefaultUrl returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponse) HasDefaultUrl() bool {
	if o != nil && o.DefaultUrl != nil {
		return true
	}

	return false
}

// SetDefaultUrl gets a reference to the given string and assigns it to the DefaultUrl field.
func (o *GetPreviewStreamsResponse) SetDefaultUrl(v string) {
	o.DefaultUrl = &v
}

// GetDefaultVideoTrack returns the DefaultVideoTrack field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponse) GetDefaultVideoTrack() GetPreviewStreamsResponseDefaultVideoTrack {
	if o == nil || o.DefaultVideoTrack == nil {
		var ret GetPreviewStreamsResponseDefaultVideoTrack
		return ret
	}
	return *o.DefaultVideoTrack
}

// GetDefaultVideoTrackOk returns a tuple with the DefaultVideoTrack field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponse) GetDefaultVideoTrackOk() (*GetPreviewStreamsResponseDefaultVideoTrack, bool) {
	if o == nil || o.DefaultVideoTrack == nil {
		return nil, false
	}
	return o.DefaultVideoTrack, true
}

// HasDefaultVideoTrack returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponse) HasDefaultVideoTrack() bool {
	if o != nil && o.DefaultVideoTrack != nil {
		return true
	}

	return false
}

// SetDefaultVideoTrack gets a reference to the given GetPreviewStreamsResponseDefaultVideoTrack and assigns it to the DefaultVideoTrack field.
func (o *GetPreviewStreamsResponse) SetDefaultVideoTrack(v GetPreviewStreamsResponseDefaultVideoTrack) {
	o.DefaultVideoTrack = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponse) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponse) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponse) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *GetPreviewStreamsResponse) SetToken(v string) {
	o.Token = &v
}

// GetVideoTracks returns the VideoTracks field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponse) GetVideoTracks() []GetPreviewStreamsResponseDefaultVideoTrack {
	if o == nil || o.VideoTracks == nil {
		var ret []GetPreviewStreamsResponseDefaultVideoTrack
		return ret
	}
	return o.VideoTracks
}

// GetVideoTracksOk returns a tuple with the VideoTracks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponse) GetVideoTracksOk() ([]GetPreviewStreamsResponseDefaultVideoTrack, bool) {
	if o == nil || o.VideoTracks == nil {
		return nil, false
	}
	return o.VideoTracks, true
}

// HasVideoTracks returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponse) HasVideoTracks() bool {
	if o != nil && o.VideoTracks != nil {
		return true
	}

	return false
}

// SetVideoTracks gets a reference to the given []GetPreviewStreamsResponseDefaultVideoTrack and assigns it to the VideoTracks field.
func (o *GetPreviewStreamsResponse) SetVideoTracks(v []GetPreviewStreamsResponseDefaultVideoTrack) {
	o.VideoTracks = v
}

func (o GetPreviewStreamsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Schema != nil {
		toSerialize["$schema"] = o.Schema
	}
	if o.AudioTracks != nil {
		toSerialize["audio_tracks"] = o.AudioTracks
	}
	if o.DefaultAudioTrack != nil {
		toSerialize["default_audio_track"] = o.DefaultAudioTrack
	}
	if o.DefaultUrl != nil {
		toSerialize["default_url"] = o.DefaultUrl
	}
	if o.DefaultVideoTrack != nil {
		toSerialize["default_video_track"] = o.DefaultVideoTrack
	}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	if o.VideoTracks != nil {
		toSerialize["video_tracks"] = o.VideoTracks
	}
	return json.Marshal(toSerialize)
}

type NullableGetPreviewStreamsResponse struct {
	value *GetPreviewStreamsResponse
	isSet bool
}

func (v NullableGetPreviewStreamsResponse) Get() *GetPreviewStreamsResponse {
	return v.value
}

func (v *NullableGetPreviewStreamsResponse) Set(val *GetPreviewStreamsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPreviewStreamsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPreviewStreamsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPreviewStreamsResponse(val *GetPreviewStreamsResponse) *NullableGetPreviewStreamsResponse {
	return &NullableGetPreviewStreamsResponse{value: val, isSet: true}
}

func (v NullableGetPreviewStreamsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPreviewStreamsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


