/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the SignalingExplicitTier type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SignalingExplicitTier{}

// SignalingExplicitTier struct for SignalingExplicitTier
type SignalingExplicitTier struct {
	Values []int32 `json:"values,omitempty" format:"int32"`
}

// NewSignalingExplicitTier instantiates a new SignalingExplicitTier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSignalingExplicitTier() *SignalingExplicitTier {
	this := SignalingExplicitTier{}
	return &this
}

// NewSignalingExplicitTierWithDefaults instantiates a new SignalingExplicitTier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignalingExplicitTierWithDefaults() *SignalingExplicitTier {
	this := SignalingExplicitTier{}
	return &this
}

// GetValues returns the Values field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SignalingExplicitTier) GetValues() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SignalingExplicitTier) GetValuesOk() ([]int32, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *SignalingExplicitTier) HasValues() bool {
	if o != nil && IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []int32 and assigns it to the Values field.
func (o *SignalingExplicitTier) SetValues(v []int32) {
	o.Values = v
}

func (o SignalingExplicitTier) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SignalingExplicitTier) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Values != nil {
		toSerialize["values"] = o.Values
	}
	return toSerialize, nil
}

type NullableSignalingExplicitTier struct {
	value *SignalingExplicitTier
	isSet bool
}

func (v NullableSignalingExplicitTier) Get() *SignalingExplicitTier {
	return v.value
}

func (v *NullableSignalingExplicitTier) Set(val *SignalingExplicitTier) {
	v.value = val
	v.isSet = true
}

func (v NullableSignalingExplicitTier) IsSet() bool {
	return v.isSet
}

func (v *NullableSignalingExplicitTier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSignalingExplicitTier(val *SignalingExplicitTier) *NullableSignalingExplicitTier {
	return &NullableSignalingExplicitTier{value: val, isSet: true}
}

func (v NullableSignalingExplicitTier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSignalingExplicitTier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
