/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the PutQCURequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PutQCURequest{}

// PutQCURequest struct for PutQCURequest
type PutQCURequest struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty" format:"uri" doc:"A URL to the JSON Schema for this object."`
	// Correlation ID for this QCU request
	CorrelationId string `json:"correlation_id" doc:"Correlation ID for this QCU request"`
	// List of moments to process
	Moments      []Moment            `json:"moments" doc:"List of moments to process"`
	Notification DynamicNotification `json:"notification"`
	// Optional key/value configuration pairs
	Options *map[string]string `json:"options,omitempty" doc:"Optional key/value configuration pairs"`
	// Order of the QCU request for an event, 1-based
	RequestNumber int64 `json:"request_number" format:"int64" doc:"Order of the QCU request for an event, 1-based"`
}

// NewPutQCURequest instantiates a new PutQCURequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPutQCURequest(correlationId string, moments []Moment, notification DynamicNotification, requestNumber int64) *PutQCURequest {
	this := PutQCURequest{}
	this.CorrelationId = correlationId
	this.Moments = moments
	this.Notification = notification
	this.RequestNumber = requestNumber
	return &this
}

// NewPutQCURequestWithDefaults instantiates a new PutQCURequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPutQCURequestWithDefaults() *PutQCURequest {
	this := PutQCURequest{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *PutQCURequest) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutQCURequest) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *PutQCURequest) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *PutQCURequest) SetSchema(v string) {
	o.Schema = &v
}

// GetCorrelationId returns the CorrelationId field value
func (o *PutQCURequest) GetCorrelationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CorrelationId
}

// GetCorrelationIdOk returns a tuple with the CorrelationId field value
// and a boolean to check if the value has been set.
func (o *PutQCURequest) GetCorrelationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CorrelationId, true
}

// SetCorrelationId sets field value
func (o *PutQCURequest) SetCorrelationId(v string) {
	o.CorrelationId = v
}

// GetMoments returns the Moments field value
// If the value is explicit nil, the zero value for []Moment will be returned
func (o *PutQCURequest) GetMoments() []Moment {
	if o == nil {
		var ret []Moment
		return ret
	}

	return o.Moments
}

// GetMomentsOk returns a tuple with the Moments field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PutQCURequest) GetMomentsOk() ([]Moment, bool) {
	if o == nil || IsNil(o.Moments) {
		return nil, false
	}
	return o.Moments, true
}

// SetMoments sets field value
func (o *PutQCURequest) SetMoments(v []Moment) {
	o.Moments = v
}

// GetNotification returns the Notification field value
func (o *PutQCURequest) GetNotification() DynamicNotification {
	if o == nil {
		var ret DynamicNotification
		return ret
	}

	return o.Notification
}

// GetNotificationOk returns a tuple with the Notification field value
// and a boolean to check if the value has been set.
func (o *PutQCURequest) GetNotificationOk() (*DynamicNotification, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Notification, true
}

// SetNotification sets field value
func (o *PutQCURequest) SetNotification(v DynamicNotification) {
	o.Notification = v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *PutQCURequest) GetOptions() map[string]string {
	if o == nil || IsNil(o.Options) {
		var ret map[string]string
		return ret
	}
	return *o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PutQCURequest) GetOptionsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *PutQCURequest) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given map[string]string and assigns it to the Options field.
func (o *PutQCURequest) SetOptions(v map[string]string) {
	o.Options = &v
}

// GetRequestNumber returns the RequestNumber field value
func (o *PutQCURequest) GetRequestNumber() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RequestNumber
}

// GetRequestNumberOk returns a tuple with the RequestNumber field value
// and a boolean to check if the value has been set.
func (o *PutQCURequest) GetRequestNumberOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestNumber, true
}

// SetRequestNumber sets field value
func (o *PutQCURequest) SetRequestNumber(v int64) {
	o.RequestNumber = v
}

func (o PutQCURequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PutQCURequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["correlation_id"] = o.CorrelationId
	if o.Moments != nil {
		toSerialize["moments"] = o.Moments
	}
	toSerialize["notification"] = o.Notification
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	toSerialize["request_number"] = o.RequestNumber
	return toSerialize, nil
}

type NullablePutQCURequest struct {
	value *PutQCURequest
	isSet bool
}

func (v NullablePutQCURequest) Get() *PutQCURequest {
	return v.value
}

func (v *NullablePutQCURequest) Set(val *PutQCURequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePutQCURequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePutQCURequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePutQCURequest(val *PutQCURequest) *NullablePutQCURequest {
	return &NullablePutQCURequest{value: val, isSet: true}
}

func (v NullablePutQCURequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePutQCURequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
