/*
 * WBD Aventus Channels API
 *
 * API version: v1.19.22
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the DynamicSyndicationRequestSyndicationFilesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DynamicSyndicationRequestSyndicationFilesInner{}

// DynamicSyndicationRequestSyndicationFilesInner struct for DynamicSyndicationRequestSyndicationFilesInner
type DynamicSyndicationRequestSyndicationFilesInner struct {
	AudioEncoderId string `json:"audio_encoder_id"`
	FilePath string `json:"file_path"`
	ManifestPath *string `json:"manifest_path,omitempty"`
	VideoEncoderId *string `json:"video_encoder_id,omitempty"`
}

// NewDynamicSyndicationRequestSyndicationFilesInner instantiates a new DynamicSyndicationRequestSyndicationFilesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDynamicSyndicationRequestSyndicationFilesInner(audioEncoderId string, filePath string) *DynamicSyndicationRequestSyndicationFilesInner {
	this := DynamicSyndicationRequestSyndicationFilesInner{}
	this.AudioEncoderId = audioEncoderId
	this.FilePath = filePath
	return &this
}

// NewDynamicSyndicationRequestSyndicationFilesInnerWithDefaults instantiates a new DynamicSyndicationRequestSyndicationFilesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDynamicSyndicationRequestSyndicationFilesInnerWithDefaults() *DynamicSyndicationRequestSyndicationFilesInner {
	this := DynamicSyndicationRequestSyndicationFilesInner{}
	return &this
}

// GetAudioEncoderId returns the AudioEncoderId field value
func (o *DynamicSyndicationRequestSyndicationFilesInner) GetAudioEncoderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AudioEncoderId
}

// GetAudioEncoderIdOk returns a tuple with the AudioEncoderId field value
// and a boolean to check if the value has been set.
func (o *DynamicSyndicationRequestSyndicationFilesInner) GetAudioEncoderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AudioEncoderId, true
}

// SetAudioEncoderId sets field value
func (o *DynamicSyndicationRequestSyndicationFilesInner) SetAudioEncoderId(v string) {
	o.AudioEncoderId = v
}

// GetFilePath returns the FilePath field value
func (o *DynamicSyndicationRequestSyndicationFilesInner) GetFilePath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilePath
}

// GetFilePathOk returns a tuple with the FilePath field value
// and a boolean to check if the value has been set.
func (o *DynamicSyndicationRequestSyndicationFilesInner) GetFilePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilePath, true
}

// SetFilePath sets field value
func (o *DynamicSyndicationRequestSyndicationFilesInner) SetFilePath(v string) {
	o.FilePath = v
}

// GetManifestPath returns the ManifestPath field value if set, zero value otherwise.
func (o *DynamicSyndicationRequestSyndicationFilesInner) GetManifestPath() string {
	if o == nil || IsNil(o.ManifestPath) {
		var ret string
		return ret
	}
	return *o.ManifestPath
}

// GetManifestPathOk returns a tuple with the ManifestPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicSyndicationRequestSyndicationFilesInner) GetManifestPathOk() (*string, bool) {
	if o == nil || IsNil(o.ManifestPath) {
		return nil, false
	}
	return o.ManifestPath, true
}

// HasManifestPath returns a boolean if a field has been set.
func (o *DynamicSyndicationRequestSyndicationFilesInner) HasManifestPath() bool {
	if o != nil && !IsNil(o.ManifestPath) {
		return true
	}

	return false
}

// SetManifestPath gets a reference to the given string and assigns it to the ManifestPath field.
func (o *DynamicSyndicationRequestSyndicationFilesInner) SetManifestPath(v string) {
	o.ManifestPath = &v
}

// GetVideoEncoderId returns the VideoEncoderId field value if set, zero value otherwise.
func (o *DynamicSyndicationRequestSyndicationFilesInner) GetVideoEncoderId() string {
	if o == nil || IsNil(o.VideoEncoderId) {
		var ret string
		return ret
	}
	return *o.VideoEncoderId
}

// GetVideoEncoderIdOk returns a tuple with the VideoEncoderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicSyndicationRequestSyndicationFilesInner) GetVideoEncoderIdOk() (*string, bool) {
	if o == nil || IsNil(o.VideoEncoderId) {
		return nil, false
	}
	return o.VideoEncoderId, true
}

// HasVideoEncoderId returns a boolean if a field has been set.
func (o *DynamicSyndicationRequestSyndicationFilesInner) HasVideoEncoderId() bool {
	if o != nil && !IsNil(o.VideoEncoderId) {
		return true
	}

	return false
}

// SetVideoEncoderId gets a reference to the given string and assigns it to the VideoEncoderId field.
func (o *DynamicSyndicationRequestSyndicationFilesInner) SetVideoEncoderId(v string) {
	o.VideoEncoderId = &v
}

func (o DynamicSyndicationRequestSyndicationFilesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DynamicSyndicationRequestSyndicationFilesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["audio_encoder_id"] = o.AudioEncoderId
	toSerialize["file_path"] = o.FilePath
	if !IsNil(o.ManifestPath) {
		toSerialize["manifest_path"] = o.ManifestPath
	}
	if !IsNil(o.VideoEncoderId) {
		toSerialize["video_encoder_id"] = o.VideoEncoderId
	}
	return toSerialize, nil
}

type NullableDynamicSyndicationRequestSyndicationFilesInner struct {
	value *DynamicSyndicationRequestSyndicationFilesInner
	isSet bool
}

func (v NullableDynamicSyndicationRequestSyndicationFilesInner) Get() *DynamicSyndicationRequestSyndicationFilesInner {
	return v.value
}

func (v *NullableDynamicSyndicationRequestSyndicationFilesInner) Set(val *DynamicSyndicationRequestSyndicationFilesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDynamicSyndicationRequestSyndicationFilesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDynamicSyndicationRequestSyndicationFilesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDynamicSyndicationRequestSyndicationFilesInner(val *DynamicSyndicationRequestSyndicationFilesInner) *NullableDynamicSyndicationRequestSyndicationFilesInner {
	return &NullableDynamicSyndicationRequestSyndicationFilesInner{value: val, isSet: true}
}

func (v NullableDynamicSyndicationRequestSyndicationFilesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDynamicSyndicationRequestSyndicationFilesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


