/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the Packaging type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Packaging{}

// Packaging struct for Packaging
type Packaging struct {
	// Defines the list of packagers available for Publications.
	Packagers map[string]PatchOrgChannelRequestPackagingPackagersValue `json:"packagers,omitempty" doc:"Defines the list of packagers available for Publications."`
}

// NewPackaging instantiates a new Packaging object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPackaging() *Packaging {
	this := Packaging{}
	return &this
}

// NewPackagingWithDefaults instantiates a new Packaging object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPackagingWithDefaults() *Packaging {
	this := Packaging{}
	return &this
}

// GetPackagers returns the Packagers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Packaging) GetPackagers() map[string]PatchOrgChannelRequestPackagingPackagersValue {
	if o == nil {
		var ret map[string]PatchOrgChannelRequestPackagingPackagersValue
		return ret
	}
	return o.Packagers
}

// GetPackagersOk returns a tuple with the Packagers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Packaging) GetPackagersOk() (*map[string]PatchOrgChannelRequestPackagingPackagersValue, bool) {
	if o == nil || IsNil(o.Packagers) {
		return nil, false
	}
	return &o.Packagers, true
}

// HasPackagers returns a boolean if a field has been set.
func (o *Packaging) HasPackagers() bool {
	if o != nil && IsNil(o.Packagers) {
		return true
	}

	return false
}

// SetPackagers gets a reference to the given map[string]PatchOrgChannelRequestPackagingPackagersValue and assigns it to the Packagers field.
func (o *Packaging) SetPackagers(v map[string]PatchOrgChannelRequestPackagingPackagersValue) {
	o.Packagers = v
}

func (o Packaging) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Packaging) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Packagers != nil {
		toSerialize["packagers"] = o.Packagers
	}
	return toSerialize, nil
}

type NullablePackaging struct {
	value *Packaging
	isSet bool
}

func (v NullablePackaging) Get() *Packaging {
	return v.value
}

func (v *NullablePackaging) Set(val *Packaging) {
	v.value = val
	v.isSet = true
}

func (v NullablePackaging) IsSet() bool {
	return v.isSet
}

func (v *NullablePackaging) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePackaging(val *Packaging) *NullablePackaging {
	return &NullablePackaging{value: val, isSet: true}
}

func (v NullablePackaging) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePackaging) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


