/*
 * WBD Aventus Channels API
 *
 * API version: v1.19.25
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the OrgSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrgSummary{}

// OrgSummary struct for OrgSummary
type OrgSummary struct {
	// ID of the organization
	Id string `json:"id" doc:"ID of the organization"`
	// Link to this resource
	Self *string `json:"self,omitempty" format:"uri" doc:"Link to this resource"`
}

// NewOrgSummary instantiates a new OrgSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgSummary(id string) *OrgSummary {
	this := OrgSummary{}
	this.Id = id
	return &this
}

// NewOrgSummaryWithDefaults instantiates a new OrgSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgSummaryWithDefaults() *OrgSummary {
	this := OrgSummary{}
	return &this
}

// GetId returns the Id field value
func (o *OrgSummary) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OrgSummary) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OrgSummary) SetId(v string) {
	o.Id = v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *OrgSummary) GetSelf() string {
	if o == nil || IsNil(o.Self) {
		var ret string
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgSummary) GetSelfOk() (*string, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *OrgSummary) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given string and assigns it to the Self field.
func (o *OrgSummary) SetSelf(v string) {
	o.Self = &v
}

func (o OrgSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrgSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	return toSerialize, nil
}

type NullableOrgSummary struct {
	value *OrgSummary
	isSet bool
}

func (v NullableOrgSummary) Get() *OrgSummary {
	return v.value
}

func (v *NullableOrgSummary) Set(val *OrgSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgSummary(val *OrgSummary) *NullableOrgSummary {
	return &NullableOrgSummary{value: val, isSet: true}
}

func (v NullableOrgSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


