/*
 * iStreamPlanet Channels API
 *
 * API version: 0.0.0
 * Contact: support@istreamplanet.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// GetPreviewStreamsResponseDefaultVideoTrack struct for GetPreviewStreamsResponseDefaultVideoTrack
type GetPreviewStreamsResponseDefaultVideoTrack struct {
	Bitrate *int32 `json:"bitrate,omitempty"`
	// codec_string will be set to the RFC 6381 compliant string that represents the specific codec in this VideoTrackInfo. ex. 'avc1.4d401e' for H.264 and 'hvc1.2.4.L150.90' for H.265. This can be used to verify track+browser compatibility.
	CodecString *string `json:"codec_string,omitempty"`
	FrameRate *float32 `json:"frame_rate,omitempty"`
	Height *int32 `json:"height,omitempty"`
	Id *int32 `json:"id,omitempty"`
	Width *int32 `json:"width,omitempty"`
}

// NewGetPreviewStreamsResponseDefaultVideoTrack instantiates a new GetPreviewStreamsResponseDefaultVideoTrack object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPreviewStreamsResponseDefaultVideoTrack() *GetPreviewStreamsResponseDefaultVideoTrack {
	this := GetPreviewStreamsResponseDefaultVideoTrack{}
	return &this
}

// NewGetPreviewStreamsResponseDefaultVideoTrackWithDefaults instantiates a new GetPreviewStreamsResponseDefaultVideoTrack object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPreviewStreamsResponseDefaultVideoTrackWithDefaults() *GetPreviewStreamsResponseDefaultVideoTrack {
	this := GetPreviewStreamsResponseDefaultVideoTrack{}
	return &this
}

// GetBitrate returns the Bitrate field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) GetBitrate() int32 {
	if o == nil || o.Bitrate == nil {
		var ret int32
		return ret
	}
	return *o.Bitrate
}

// GetBitrateOk returns a tuple with the Bitrate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) GetBitrateOk() (*int32, bool) {
	if o == nil || o.Bitrate == nil {
		return nil, false
	}
	return o.Bitrate, true
}

// HasBitrate returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) HasBitrate() bool {
	if o != nil && o.Bitrate != nil {
		return true
	}

	return false
}

// SetBitrate gets a reference to the given int32 and assigns it to the Bitrate field.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) SetBitrate(v int32) {
	o.Bitrate = &v
}

// GetCodecString returns the CodecString field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) GetCodecString() string {
	if o == nil || o.CodecString == nil {
		var ret string
		return ret
	}
	return *o.CodecString
}

// GetCodecStringOk returns a tuple with the CodecString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) GetCodecStringOk() (*string, bool) {
	if o == nil || o.CodecString == nil {
		return nil, false
	}
	return o.CodecString, true
}

// HasCodecString returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) HasCodecString() bool {
	if o != nil && o.CodecString != nil {
		return true
	}

	return false
}

// SetCodecString gets a reference to the given string and assigns it to the CodecString field.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) SetCodecString(v string) {
	o.CodecString = &v
}

// GetFrameRate returns the FrameRate field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) GetFrameRate() float32 {
	if o == nil || o.FrameRate == nil {
		var ret float32
		return ret
	}
	return *o.FrameRate
}

// GetFrameRateOk returns a tuple with the FrameRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) GetFrameRateOk() (*float32, bool) {
	if o == nil || o.FrameRate == nil {
		return nil, false
	}
	return o.FrameRate, true
}

// HasFrameRate returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) HasFrameRate() bool {
	if o != nil && o.FrameRate != nil {
		return true
	}

	return false
}

// SetFrameRate gets a reference to the given float32 and assigns it to the FrameRate field.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) SetFrameRate(v float32) {
	o.FrameRate = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) GetHeight() int32 {
	if o == nil || o.Height == nil {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) GetHeightOk() (*int32, bool) {
	if o == nil || o.Height == nil {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) HasHeight() bool {
	if o != nil && o.Height != nil {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) SetHeight(v int32) {
	o.Height = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) SetId(v int32) {
	o.Id = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) GetWidth() int32 {
	if o == nil || o.Width == nil {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) GetWidthOk() (*int32, bool) {
	if o == nil || o.Width == nil {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) HasWidth() bool {
	if o != nil && o.Width != nil {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *GetPreviewStreamsResponseDefaultVideoTrack) SetWidth(v int32) {
	o.Width = &v
}

func (o GetPreviewStreamsResponseDefaultVideoTrack) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Bitrate != nil {
		toSerialize["bitrate"] = o.Bitrate
	}
	if o.CodecString != nil {
		toSerialize["codec_string"] = o.CodecString
	}
	if o.FrameRate != nil {
		toSerialize["frame_rate"] = o.FrameRate
	}
	if o.Height != nil {
		toSerialize["height"] = o.Height
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Width != nil {
		toSerialize["width"] = o.Width
	}
	return json.Marshal(toSerialize)
}

type NullableGetPreviewStreamsResponseDefaultVideoTrack struct {
	value *GetPreviewStreamsResponseDefaultVideoTrack
	isSet bool
}

func (v NullableGetPreviewStreamsResponseDefaultVideoTrack) Get() *GetPreviewStreamsResponseDefaultVideoTrack {
	return v.value
}

func (v *NullableGetPreviewStreamsResponseDefaultVideoTrack) Set(val *GetPreviewStreamsResponseDefaultVideoTrack) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPreviewStreamsResponseDefaultVideoTrack) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPreviewStreamsResponseDefaultVideoTrack) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPreviewStreamsResponseDefaultVideoTrack(val *GetPreviewStreamsResponseDefaultVideoTrack) *NullableGetPreviewStreamsResponseDefaultVideoTrack {
	return &NullableGetPreviewStreamsResponseDefaultVideoTrack{value: val, isSet: true}
}

func (v NullableGetPreviewStreamsResponseDefaultVideoTrack) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPreviewStreamsResponseDefaultVideoTrack) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


