/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the PatchOrgChannelRequestSignalingBlackoutSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchOrgChannelRequestSignalingBlackoutSettings{}

// PatchOrgChannelRequestSignalingBlackoutSettings struct for PatchOrgChannelRequestSignalingBlackoutSettings
type PatchOrgChannelRequestSignalingBlackoutSettings struct {
	// Default slate URL to use for blackouts. Can be overridden by the 'slates' field.
	DefaultBlackoutSlateUrl interface{} `json:"default_blackout_slate_url,omitempty" format:"uri-reference" doc:"Default slate URL to use for blackouts. Can be overridden by the 'slates' field."`
	// List of signaling segment types to force blackout, e.g. add 'SPLICE_INSERT' to blackout all ads signaled via SCTE-35 splice_insert.
	ForceBlackoutSegments interface{} `json:"force_blackout_segments,omitempty" doc:"List of signaling segment types to force blackout, e.g. add 'SPLICE_INSERT' to blackout all ads signaled via SCTE-35 splice_insert."`
	// Determines whether to honor the web_delivery_allowed attribute in SCTE-35 segmentation descriptors. When this is enabled, a segmentation descriptor with web_delivery_allowed=false will trigger a blackout.
	HonorWebDeliveryRestriction interface{} `json:"honor_web_delivery_restriction,omitempty" doc:"Determines whether to honor the web_delivery_allowed attribute in SCTE-35 segmentation descriptors. When this is enabled, a segmentation descriptor with web_delivery_allowed=false will trigger a blackout."`
	// Per-segment type slate overrides.
	Slates interface{} `json:"slates,omitempty" doc:"Per-segment type slate overrides."`
}

// NewPatchOrgChannelRequestSignalingBlackoutSettings instantiates a new PatchOrgChannelRequestSignalingBlackoutSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchOrgChannelRequestSignalingBlackoutSettings() *PatchOrgChannelRequestSignalingBlackoutSettings {
	this := PatchOrgChannelRequestSignalingBlackoutSettings{}
	return &this
}

// NewPatchOrgChannelRequestSignalingBlackoutSettingsWithDefaults instantiates a new PatchOrgChannelRequestSignalingBlackoutSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchOrgChannelRequestSignalingBlackoutSettingsWithDefaults() *PatchOrgChannelRequestSignalingBlackoutSettings {
	this := PatchOrgChannelRequestSignalingBlackoutSettings{}
	return &this
}

// GetDefaultBlackoutSlateUrl returns the DefaultBlackoutSlateUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) GetDefaultBlackoutSlateUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.DefaultBlackoutSlateUrl
}

// GetDefaultBlackoutSlateUrlOk returns a tuple with the DefaultBlackoutSlateUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) GetDefaultBlackoutSlateUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DefaultBlackoutSlateUrl) {
		return nil, false
	}
	return &o.DefaultBlackoutSlateUrl, true
}

// HasDefaultBlackoutSlateUrl returns a boolean if a field has been set.
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) HasDefaultBlackoutSlateUrl() bool {
	if o != nil && IsNil(o.DefaultBlackoutSlateUrl) {
		return true
	}

	return false
}

// SetDefaultBlackoutSlateUrl gets a reference to the given interface{} and assigns it to the DefaultBlackoutSlateUrl field.
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) SetDefaultBlackoutSlateUrl(v interface{}) {
	o.DefaultBlackoutSlateUrl = v
}

// GetForceBlackoutSegments returns the ForceBlackoutSegments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) GetForceBlackoutSegments() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ForceBlackoutSegments
}

// GetForceBlackoutSegmentsOk returns a tuple with the ForceBlackoutSegments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) GetForceBlackoutSegmentsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ForceBlackoutSegments) {
		return nil, false
	}
	return &o.ForceBlackoutSegments, true
}

// HasForceBlackoutSegments returns a boolean if a field has been set.
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) HasForceBlackoutSegments() bool {
	if o != nil && IsNil(o.ForceBlackoutSegments) {
		return true
	}

	return false
}

// SetForceBlackoutSegments gets a reference to the given interface{} and assigns it to the ForceBlackoutSegments field.
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) SetForceBlackoutSegments(v interface{}) {
	o.ForceBlackoutSegments = v
}

// GetHonorWebDeliveryRestriction returns the HonorWebDeliveryRestriction field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) GetHonorWebDeliveryRestriction() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.HonorWebDeliveryRestriction
}

// GetHonorWebDeliveryRestrictionOk returns a tuple with the HonorWebDeliveryRestriction field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) GetHonorWebDeliveryRestrictionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.HonorWebDeliveryRestriction) {
		return nil, false
	}
	return &o.HonorWebDeliveryRestriction, true
}

// HasHonorWebDeliveryRestriction returns a boolean if a field has been set.
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) HasHonorWebDeliveryRestriction() bool {
	if o != nil && IsNil(o.HonorWebDeliveryRestriction) {
		return true
	}

	return false
}

// SetHonorWebDeliveryRestriction gets a reference to the given interface{} and assigns it to the HonorWebDeliveryRestriction field.
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) SetHonorWebDeliveryRestriction(v interface{}) {
	o.HonorWebDeliveryRestriction = v
}

// GetSlates returns the Slates field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) GetSlates() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Slates
}

// GetSlatesOk returns a tuple with the Slates field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) GetSlatesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Slates) {
		return nil, false
	}
	return &o.Slates, true
}

// HasSlates returns a boolean if a field has been set.
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) HasSlates() bool {
	if o != nil && IsNil(o.Slates) {
		return true
	}

	return false
}

// SetSlates gets a reference to the given interface{} and assigns it to the Slates field.
func (o *PatchOrgChannelRequestSignalingBlackoutSettings) SetSlates(v interface{}) {
	o.Slates = v
}

func (o PatchOrgChannelRequestSignalingBlackoutSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchOrgChannelRequestSignalingBlackoutSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.DefaultBlackoutSlateUrl != nil {
		toSerialize["default_blackout_slate_url"] = o.DefaultBlackoutSlateUrl
	}
	if o.ForceBlackoutSegments != nil {
		toSerialize["force_blackout_segments"] = o.ForceBlackoutSegments
	}
	if o.HonorWebDeliveryRestriction != nil {
		toSerialize["honor_web_delivery_restriction"] = o.HonorWebDeliveryRestriction
	}
	if o.Slates != nil {
		toSerialize["slates"] = o.Slates
	}
	return toSerialize, nil
}

type NullablePatchOrgChannelRequestSignalingBlackoutSettings struct {
	value *PatchOrgChannelRequestSignalingBlackoutSettings
	isSet bool
}

func (v NullablePatchOrgChannelRequestSignalingBlackoutSettings) Get() *PatchOrgChannelRequestSignalingBlackoutSettings {
	return v.value
}

func (v *NullablePatchOrgChannelRequestSignalingBlackoutSettings) Set(val *PatchOrgChannelRequestSignalingBlackoutSettings) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchOrgChannelRequestSignalingBlackoutSettings) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchOrgChannelRequestSignalingBlackoutSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchOrgChannelRequestSignalingBlackoutSettings(val *PatchOrgChannelRequestSignalingBlackoutSettings) *NullablePatchOrgChannelRequestSignalingBlackoutSettings {
	return &NullablePatchOrgChannelRequestSignalingBlackoutSettings{value: val, isSet: true}
}

func (v NullablePatchOrgChannelRequestSignalingBlackoutSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchOrgChannelRequestSignalingBlackoutSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


