/*
 * iStreamPlanet Channels API
 *
 * API version: 0.0.0
 * Contact: support@istreamplanet.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// ChannelPackagingPackagersValueContentProtection Configures how to protect packaged media segments.
type ChannelPackagingPackagersValueContentProtection struct {
	Atlas *ChannelPackagingPackagersValueContentProtectionAtlas `json:"atlas,omitempty"`
	BulkFile *ChannelPackagingPackagersValueContentProtectionBulkFile `json:"bulk_file,omitempty"`
	Common *ChannelPackagingPackagersValueContentProtectionCommon `json:"common,omitempty"`
	Cpix *ChannelPackagingPackagersValueContentProtectionCpix `json:"cpix,omitempty"`
	KeyRotation *ChannelPackagingPackagersValueContentProtectionKeyRotation `json:"key_rotation,omitempty"`
	// Only one of ['bulk_file', 'sample_aes', 'common'] may be set.
	SampleAes map[string]interface{} `json:"sample_aes,omitempty"`
	Simple *ChannelPackagingPackagersValueContentProtectionSimple `json:"simple,omitempty"`
}

// NewChannelPackagingPackagersValueContentProtection instantiates a new ChannelPackagingPackagersValueContentProtection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelPackagingPackagersValueContentProtection() *ChannelPackagingPackagersValueContentProtection {
	this := ChannelPackagingPackagersValueContentProtection{}
	return &this
}

// NewChannelPackagingPackagersValueContentProtectionWithDefaults instantiates a new ChannelPackagingPackagersValueContentProtection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelPackagingPackagersValueContentProtectionWithDefaults() *ChannelPackagingPackagersValueContentProtection {
	this := ChannelPackagingPackagersValueContentProtection{}
	return &this
}

// GetAtlas returns the Atlas field value if set, zero value otherwise.
func (o *ChannelPackagingPackagersValueContentProtection) GetAtlas() ChannelPackagingPackagersValueContentProtectionAtlas {
	if o == nil || o.Atlas == nil {
		var ret ChannelPackagingPackagersValueContentProtectionAtlas
		return ret
	}
	return *o.Atlas
}

// GetAtlasOk returns a tuple with the Atlas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelPackagingPackagersValueContentProtection) GetAtlasOk() (*ChannelPackagingPackagersValueContentProtectionAtlas, bool) {
	if o == nil || o.Atlas == nil {
		return nil, false
	}
	return o.Atlas, true
}

// HasAtlas returns a boolean if a field has been set.
func (o *ChannelPackagingPackagersValueContentProtection) HasAtlas() bool {
	if o != nil && o.Atlas != nil {
		return true
	}

	return false
}

// SetAtlas gets a reference to the given ChannelPackagingPackagersValueContentProtectionAtlas and assigns it to the Atlas field.
func (o *ChannelPackagingPackagersValueContentProtection) SetAtlas(v ChannelPackagingPackagersValueContentProtectionAtlas) {
	o.Atlas = &v
}

// GetBulkFile returns the BulkFile field value if set, zero value otherwise.
func (o *ChannelPackagingPackagersValueContentProtection) GetBulkFile() ChannelPackagingPackagersValueContentProtectionBulkFile {
	if o == nil || o.BulkFile == nil {
		var ret ChannelPackagingPackagersValueContentProtectionBulkFile
		return ret
	}
	return *o.BulkFile
}

// GetBulkFileOk returns a tuple with the BulkFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelPackagingPackagersValueContentProtection) GetBulkFileOk() (*ChannelPackagingPackagersValueContentProtectionBulkFile, bool) {
	if o == nil || o.BulkFile == nil {
		return nil, false
	}
	return o.BulkFile, true
}

// HasBulkFile returns a boolean if a field has been set.
func (o *ChannelPackagingPackagersValueContentProtection) HasBulkFile() bool {
	if o != nil && o.BulkFile != nil {
		return true
	}

	return false
}

// SetBulkFile gets a reference to the given ChannelPackagingPackagersValueContentProtectionBulkFile and assigns it to the BulkFile field.
func (o *ChannelPackagingPackagersValueContentProtection) SetBulkFile(v ChannelPackagingPackagersValueContentProtectionBulkFile) {
	o.BulkFile = &v
}

// GetCommon returns the Common field value if set, zero value otherwise.
func (o *ChannelPackagingPackagersValueContentProtection) GetCommon() ChannelPackagingPackagersValueContentProtectionCommon {
	if o == nil || o.Common == nil {
		var ret ChannelPackagingPackagersValueContentProtectionCommon
		return ret
	}
	return *o.Common
}

// GetCommonOk returns a tuple with the Common field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelPackagingPackagersValueContentProtection) GetCommonOk() (*ChannelPackagingPackagersValueContentProtectionCommon, bool) {
	if o == nil || o.Common == nil {
		return nil, false
	}
	return o.Common, true
}

// HasCommon returns a boolean if a field has been set.
func (o *ChannelPackagingPackagersValueContentProtection) HasCommon() bool {
	if o != nil && o.Common != nil {
		return true
	}

	return false
}

// SetCommon gets a reference to the given ChannelPackagingPackagersValueContentProtectionCommon and assigns it to the Common field.
func (o *ChannelPackagingPackagersValueContentProtection) SetCommon(v ChannelPackagingPackagersValueContentProtectionCommon) {
	o.Common = &v
}

// GetCpix returns the Cpix field value if set, zero value otherwise.
func (o *ChannelPackagingPackagersValueContentProtection) GetCpix() ChannelPackagingPackagersValueContentProtectionCpix {
	if o == nil || o.Cpix == nil {
		var ret ChannelPackagingPackagersValueContentProtectionCpix
		return ret
	}
	return *o.Cpix
}

// GetCpixOk returns a tuple with the Cpix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelPackagingPackagersValueContentProtection) GetCpixOk() (*ChannelPackagingPackagersValueContentProtectionCpix, bool) {
	if o == nil || o.Cpix == nil {
		return nil, false
	}
	return o.Cpix, true
}

// HasCpix returns a boolean if a field has been set.
func (o *ChannelPackagingPackagersValueContentProtection) HasCpix() bool {
	if o != nil && o.Cpix != nil {
		return true
	}

	return false
}

// SetCpix gets a reference to the given ChannelPackagingPackagersValueContentProtectionCpix and assigns it to the Cpix field.
func (o *ChannelPackagingPackagersValueContentProtection) SetCpix(v ChannelPackagingPackagersValueContentProtectionCpix) {
	o.Cpix = &v
}

// GetKeyRotation returns the KeyRotation field value if set, zero value otherwise.
func (o *ChannelPackagingPackagersValueContentProtection) GetKeyRotation() ChannelPackagingPackagersValueContentProtectionKeyRotation {
	if o == nil || o.KeyRotation == nil {
		var ret ChannelPackagingPackagersValueContentProtectionKeyRotation
		return ret
	}
	return *o.KeyRotation
}

// GetKeyRotationOk returns a tuple with the KeyRotation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelPackagingPackagersValueContentProtection) GetKeyRotationOk() (*ChannelPackagingPackagersValueContentProtectionKeyRotation, bool) {
	if o == nil || o.KeyRotation == nil {
		return nil, false
	}
	return o.KeyRotation, true
}

// HasKeyRotation returns a boolean if a field has been set.
func (o *ChannelPackagingPackagersValueContentProtection) HasKeyRotation() bool {
	if o != nil && o.KeyRotation != nil {
		return true
	}

	return false
}

// SetKeyRotation gets a reference to the given ChannelPackagingPackagersValueContentProtectionKeyRotation and assigns it to the KeyRotation field.
func (o *ChannelPackagingPackagersValueContentProtection) SetKeyRotation(v ChannelPackagingPackagersValueContentProtectionKeyRotation) {
	o.KeyRotation = &v
}

// GetSampleAes returns the SampleAes field value if set, zero value otherwise.
func (o *ChannelPackagingPackagersValueContentProtection) GetSampleAes() map[string]interface{} {
	if o == nil || o.SampleAes == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.SampleAes
}

// GetSampleAesOk returns a tuple with the SampleAes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelPackagingPackagersValueContentProtection) GetSampleAesOk() (map[string]interface{}, bool) {
	if o == nil || o.SampleAes == nil {
		return nil, false
	}
	return o.SampleAes, true
}

// HasSampleAes returns a boolean if a field has been set.
func (o *ChannelPackagingPackagersValueContentProtection) HasSampleAes() bool {
	if o != nil && o.SampleAes != nil {
		return true
	}

	return false
}

// SetSampleAes gets a reference to the given map[string]interface{} and assigns it to the SampleAes field.
func (o *ChannelPackagingPackagersValueContentProtection) SetSampleAes(v map[string]interface{}) {
	o.SampleAes = v
}

// GetSimple returns the Simple field value if set, zero value otherwise.
func (o *ChannelPackagingPackagersValueContentProtection) GetSimple() ChannelPackagingPackagersValueContentProtectionSimple {
	if o == nil || o.Simple == nil {
		var ret ChannelPackagingPackagersValueContentProtectionSimple
		return ret
	}
	return *o.Simple
}

// GetSimpleOk returns a tuple with the Simple field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelPackagingPackagersValueContentProtection) GetSimpleOk() (*ChannelPackagingPackagersValueContentProtectionSimple, bool) {
	if o == nil || o.Simple == nil {
		return nil, false
	}
	return o.Simple, true
}

// HasSimple returns a boolean if a field has been set.
func (o *ChannelPackagingPackagersValueContentProtection) HasSimple() bool {
	if o != nil && o.Simple != nil {
		return true
	}

	return false
}

// SetSimple gets a reference to the given ChannelPackagingPackagersValueContentProtectionSimple and assigns it to the Simple field.
func (o *ChannelPackagingPackagersValueContentProtection) SetSimple(v ChannelPackagingPackagersValueContentProtectionSimple) {
	o.Simple = &v
}

func (o ChannelPackagingPackagersValueContentProtection) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Atlas != nil {
		toSerialize["atlas"] = o.Atlas
	}
	if o.BulkFile != nil {
		toSerialize["bulk_file"] = o.BulkFile
	}
	if o.Common != nil {
		toSerialize["common"] = o.Common
	}
	if o.Cpix != nil {
		toSerialize["cpix"] = o.Cpix
	}
	if o.KeyRotation != nil {
		toSerialize["key_rotation"] = o.KeyRotation
	}
	if o.SampleAes != nil {
		toSerialize["sample_aes"] = o.SampleAes
	}
	if o.Simple != nil {
		toSerialize["simple"] = o.Simple
	}
	return json.Marshal(toSerialize)
}

type NullableChannelPackagingPackagersValueContentProtection struct {
	value *ChannelPackagingPackagersValueContentProtection
	isSet bool
}

func (v NullableChannelPackagingPackagersValueContentProtection) Get() *ChannelPackagingPackagersValueContentProtection {
	return v.value
}

func (v *NullableChannelPackagingPackagersValueContentProtection) Set(val *ChannelPackagingPackagersValueContentProtection) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelPackagingPackagersValueContentProtection) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelPackagingPackagersValueContentProtection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelPackagingPackagersValueContentProtection(val *ChannelPackagingPackagersValueContentProtection) *NullableChannelPackagingPackagersValueContentProtection {
	return &NullableChannelPackagingPackagersValueContentProtection{value: val, isSet: true}
}

func (v NullableChannelPackagingPackagersValueContentProtection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelPackagingPackagersValueContentProtection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


