/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the Startover type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Startover{}

// Startover struct for Startover
type Startover struct {
	FirstProgramStart *map[string]interface{}                                               `json:"first_program_start,omitempty"`
	OnAiringId        *PatchOrgChannelRequestPublishingPublicationsInnerStartoverOnAiringId `json:"on_airing_id,omitempty"`
}

// NewStartover instantiates a new Startover object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartover() *Startover {
	this := Startover{}
	return &this
}

// NewStartoverWithDefaults instantiates a new Startover object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartoverWithDefaults() *Startover {
	this := Startover{}
	return &this
}

// GetFirstProgramStart returns the FirstProgramStart field value if set, zero value otherwise.
func (o *Startover) GetFirstProgramStart() map[string]interface{} {
	if o == nil || IsNil(o.FirstProgramStart) {
		var ret map[string]interface{}
		return ret
	}
	return *o.FirstProgramStart
}

// GetFirstProgramStartOk returns a tuple with the FirstProgramStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Startover) GetFirstProgramStartOk() (*map[string]interface{}, bool) {
	if o == nil || IsNil(o.FirstProgramStart) {
		return nil, false
	}
	return o.FirstProgramStart, true
}

// HasFirstProgramStart returns a boolean if a field has been set.
func (o *Startover) HasFirstProgramStart() bool {
	if o != nil && !IsNil(o.FirstProgramStart) {
		return true
	}

	return false
}

// SetFirstProgramStart gets a reference to the given map[string]interface{} and assigns it to the FirstProgramStart field.
func (o *Startover) SetFirstProgramStart(v map[string]interface{}) {
	o.FirstProgramStart = &v
}

// GetOnAiringId returns the OnAiringId field value if set, zero value otherwise.
func (o *Startover) GetOnAiringId() PatchOrgChannelRequestPublishingPublicationsInnerStartoverOnAiringId {
	if o == nil || IsNil(o.OnAiringId) {
		var ret PatchOrgChannelRequestPublishingPublicationsInnerStartoverOnAiringId
		return ret
	}
	return *o.OnAiringId
}

// GetOnAiringIdOk returns a tuple with the OnAiringId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Startover) GetOnAiringIdOk() (*PatchOrgChannelRequestPublishingPublicationsInnerStartoverOnAiringId, bool) {
	if o == nil || IsNil(o.OnAiringId) {
		return nil, false
	}
	return o.OnAiringId, true
}

// HasOnAiringId returns a boolean if a field has been set.
func (o *Startover) HasOnAiringId() bool {
	if o != nil && !IsNil(o.OnAiringId) {
		return true
	}

	return false
}

// SetOnAiringId gets a reference to the given PatchOrgChannelRequestPublishingPublicationsInnerStartoverOnAiringId and assigns it to the OnAiringId field.
func (o *Startover) SetOnAiringId(v PatchOrgChannelRequestPublishingPublicationsInnerStartoverOnAiringId) {
	o.OnAiringId = &v
}

func (o Startover) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Startover) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstProgramStart) {
		toSerialize["first_program_start"] = o.FirstProgramStart
	}
	if !IsNil(o.OnAiringId) {
		toSerialize["on_airing_id"] = o.OnAiringId
	}
	return toSerialize, nil
}

type NullableStartover struct {
	value *Startover
	isSet bool
}

func (v NullableStartover) Get() *Startover {
	return v.value
}

func (v *NullableStartover) Set(val *Startover) {
	v.value = val
	v.isSet = true
}

func (v NullableStartover) IsSet() bool {
	return v.isSet
}

func (v *NullableStartover) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartover(val *Startover) *NullableStartover {
	return &NullableStartover{value: val, isSet: true}
}

func (v NullableStartover) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartover) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
