/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1{}

// PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1 struct for PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1
type PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1 struct {
	// Configure the HDR settings.
	Hdr interface{} `json:"hdr,omitempty" doc:"Configure the HDR settings."`
}

// NewPatchOrgChannelRequestTranscodeVideoEncodersInnerAv1 instantiates a new PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchOrgChannelRequestTranscodeVideoEncodersInnerAv1() *PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1 {
	this := PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1{}
	return &this
}

// NewPatchOrgChannelRequestTranscodeVideoEncodersInnerAv1WithDefaults instantiates a new PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchOrgChannelRequestTranscodeVideoEncodersInnerAv1WithDefaults() *PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1 {
	this := PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1{}
	return &this
}

// GetHdr returns the Hdr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) GetHdr() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Hdr
}

// GetHdrOk returns a tuple with the Hdr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) GetHdrOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Hdr) {
		return nil, false
	}
	return &o.Hdr, true
}

// HasHdr returns a boolean if a field has been set.
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) HasHdr() bool {
	if o != nil && IsNil(o.Hdr) {
		return true
	}

	return false
}

// SetHdr gets a reference to the given interface{} and assigns it to the Hdr field.
func (o *PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) SetHdr(v interface{}) {
	o.Hdr = v
}

func (o PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Hdr != nil {
		toSerialize["hdr"] = o.Hdr
	}
	return toSerialize, nil
}

type NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerAv1 struct {
	value *PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1
	isSet bool
}

func (v NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) Get() *PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1 {
	return v.value
}

func (v *NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) Set(val *PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchOrgChannelRequestTranscodeVideoEncodersInnerAv1(val *PatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) *NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerAv1 {
	return &NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerAv1{value: val, isSet: true}
}

func (v NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchOrgChannelRequestTranscodeVideoEncodersInnerAv1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
