/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the GlobalArchiveSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GlobalArchiveSettings{}

// GlobalArchiveSettings struct for GlobalArchiveSettings
type GlobalArchiveSettings struct {
	AesKeyConversion interface{} `json:"aes_key_conversion,omitempty"`
	EnforceCustomMp4Path interface{} `json:"enforce_custom_mp4_path,omitempty"`
	MasterUrlType interface{} `json:"master_url_type,omitempty"`
	MediaUrlType interface{} `json:"media_url_type,omitempty"`
	Origins map[string]ClientOrigin `json:"origins,omitempty"`
	PreservePublishedDirectoryStructure interface{} `json:"preserve_published_directory_structure,omitempty"`
	UrlType interface{} `json:"url_type,omitempty"`
}

// NewGlobalArchiveSettings instantiates a new GlobalArchiveSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGlobalArchiveSettings() *GlobalArchiveSettings {
	this := GlobalArchiveSettings{}
	return &this
}

// NewGlobalArchiveSettingsWithDefaults instantiates a new GlobalArchiveSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGlobalArchiveSettingsWithDefaults() *GlobalArchiveSettings {
	this := GlobalArchiveSettings{}
	return &this
}

// GetAesKeyConversion returns the AesKeyConversion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalArchiveSettings) GetAesKeyConversion() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.AesKeyConversion
}

// GetAesKeyConversionOk returns a tuple with the AesKeyConversion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalArchiveSettings) GetAesKeyConversionOk() (*interface{}, bool) {
	if o == nil || IsNil(o.AesKeyConversion) {
		return nil, false
	}
	return &o.AesKeyConversion, true
}

// HasAesKeyConversion returns a boolean if a field has been set.
func (o *GlobalArchiveSettings) HasAesKeyConversion() bool {
	if o != nil && IsNil(o.AesKeyConversion) {
		return true
	}

	return false
}

// SetAesKeyConversion gets a reference to the given interface{} and assigns it to the AesKeyConversion field.
func (o *GlobalArchiveSettings) SetAesKeyConversion(v interface{}) {
	o.AesKeyConversion = v
}

// GetEnforceCustomMp4Path returns the EnforceCustomMp4Path field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalArchiveSettings) GetEnforceCustomMp4Path() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.EnforceCustomMp4Path
}

// GetEnforceCustomMp4PathOk returns a tuple with the EnforceCustomMp4Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalArchiveSettings) GetEnforceCustomMp4PathOk() (*interface{}, bool) {
	if o == nil || IsNil(o.EnforceCustomMp4Path) {
		return nil, false
	}
	return &o.EnforceCustomMp4Path, true
}

// HasEnforceCustomMp4Path returns a boolean if a field has been set.
func (o *GlobalArchiveSettings) HasEnforceCustomMp4Path() bool {
	if o != nil && IsNil(o.EnforceCustomMp4Path) {
		return true
	}

	return false
}

// SetEnforceCustomMp4Path gets a reference to the given interface{} and assigns it to the EnforceCustomMp4Path field.
func (o *GlobalArchiveSettings) SetEnforceCustomMp4Path(v interface{}) {
	o.EnforceCustomMp4Path = v
}

// GetMasterUrlType returns the MasterUrlType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalArchiveSettings) GetMasterUrlType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.MasterUrlType
}

// GetMasterUrlTypeOk returns a tuple with the MasterUrlType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalArchiveSettings) GetMasterUrlTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.MasterUrlType) {
		return nil, false
	}
	return &o.MasterUrlType, true
}

// HasMasterUrlType returns a boolean if a field has been set.
func (o *GlobalArchiveSettings) HasMasterUrlType() bool {
	if o != nil && IsNil(o.MasterUrlType) {
		return true
	}

	return false
}

// SetMasterUrlType gets a reference to the given interface{} and assigns it to the MasterUrlType field.
func (o *GlobalArchiveSettings) SetMasterUrlType(v interface{}) {
	o.MasterUrlType = v
}

// GetMediaUrlType returns the MediaUrlType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalArchiveSettings) GetMediaUrlType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.MediaUrlType
}

// GetMediaUrlTypeOk returns a tuple with the MediaUrlType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalArchiveSettings) GetMediaUrlTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.MediaUrlType) {
		return nil, false
	}
	return &o.MediaUrlType, true
}

// HasMediaUrlType returns a boolean if a field has been set.
func (o *GlobalArchiveSettings) HasMediaUrlType() bool {
	if o != nil && IsNil(o.MediaUrlType) {
		return true
	}

	return false
}

// SetMediaUrlType gets a reference to the given interface{} and assigns it to the MediaUrlType field.
func (o *GlobalArchiveSettings) SetMediaUrlType(v interface{}) {
	o.MediaUrlType = v
}

// GetOrigins returns the Origins field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalArchiveSettings) GetOrigins() map[string]ClientOrigin {
	if o == nil {
		var ret map[string]ClientOrigin
		return ret
	}
	return o.Origins
}

// GetOriginsOk returns a tuple with the Origins field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalArchiveSettings) GetOriginsOk() (*map[string]ClientOrigin, bool) {
	if o == nil || IsNil(o.Origins) {
		return nil, false
	}
	return &o.Origins, true
}

// HasOrigins returns a boolean if a field has been set.
func (o *GlobalArchiveSettings) HasOrigins() bool {
	if o != nil && IsNil(o.Origins) {
		return true
	}

	return false
}

// SetOrigins gets a reference to the given map[string]ClientOrigin and assigns it to the Origins field.
func (o *GlobalArchiveSettings) SetOrigins(v map[string]ClientOrigin) {
	o.Origins = v
}

// GetPreservePublishedDirectoryStructure returns the PreservePublishedDirectoryStructure field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalArchiveSettings) GetPreservePublishedDirectoryStructure() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PreservePublishedDirectoryStructure
}

// GetPreservePublishedDirectoryStructureOk returns a tuple with the PreservePublishedDirectoryStructure field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalArchiveSettings) GetPreservePublishedDirectoryStructureOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PreservePublishedDirectoryStructure) {
		return nil, false
	}
	return &o.PreservePublishedDirectoryStructure, true
}

// HasPreservePublishedDirectoryStructure returns a boolean if a field has been set.
func (o *GlobalArchiveSettings) HasPreservePublishedDirectoryStructure() bool {
	if o != nil && IsNil(o.PreservePublishedDirectoryStructure) {
		return true
	}

	return false
}

// SetPreservePublishedDirectoryStructure gets a reference to the given interface{} and assigns it to the PreservePublishedDirectoryStructure field.
func (o *GlobalArchiveSettings) SetPreservePublishedDirectoryStructure(v interface{}) {
	o.PreservePublishedDirectoryStructure = v
}

// GetUrlType returns the UrlType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalArchiveSettings) GetUrlType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.UrlType
}

// GetUrlTypeOk returns a tuple with the UrlType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalArchiveSettings) GetUrlTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.UrlType) {
		return nil, false
	}
	return &o.UrlType, true
}

// HasUrlType returns a boolean if a field has been set.
func (o *GlobalArchiveSettings) HasUrlType() bool {
	if o != nil && IsNil(o.UrlType) {
		return true
	}

	return false
}

// SetUrlType gets a reference to the given interface{} and assigns it to the UrlType field.
func (o *GlobalArchiveSettings) SetUrlType(v interface{}) {
	o.UrlType = v
}

func (o GlobalArchiveSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GlobalArchiveSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AesKeyConversion != nil {
		toSerialize["aes_key_conversion"] = o.AesKeyConversion
	}
	if o.EnforceCustomMp4Path != nil {
		toSerialize["enforce_custom_mp4_path"] = o.EnforceCustomMp4Path
	}
	if o.MasterUrlType != nil {
		toSerialize["master_url_type"] = o.MasterUrlType
	}
	if o.MediaUrlType != nil {
		toSerialize["media_url_type"] = o.MediaUrlType
	}
	if o.Origins != nil {
		toSerialize["origins"] = o.Origins
	}
	if o.PreservePublishedDirectoryStructure != nil {
		toSerialize["preserve_published_directory_structure"] = o.PreservePublishedDirectoryStructure
	}
	if o.UrlType != nil {
		toSerialize["url_type"] = o.UrlType
	}
	return toSerialize, nil
}

type NullableGlobalArchiveSettings struct {
	value *GlobalArchiveSettings
	isSet bool
}

func (v NullableGlobalArchiveSettings) Get() *GlobalArchiveSettings {
	return v.value
}

func (v *NullableGlobalArchiveSettings) Set(val *GlobalArchiveSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableGlobalArchiveSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableGlobalArchiveSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGlobalArchiveSettings(val *GlobalArchiveSettings) *NullableGlobalArchiveSettings {
	return &NullableGlobalArchiveSettings{value: val, isSet: true}
}

func (v NullableGlobalArchiveSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGlobalArchiveSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


