/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the MP4URLResponseBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MP4URLResponseBody{}

// MP4URLResponseBody struct for MP4URLResponseBody
type MP4URLResponseBody struct {
	// A URL to the JSON Schema for this object.
	Schema interface{} `json:"$schema,omitempty" format:"uri" doc:"A URL to the JSON Schema for this object."`
	// URL for mp4 of a clip
	Mp4url interface{} `json:"mp4url" doc:"URL for mp4 of a clip"`
}

// NewMP4URLResponseBody instantiates a new MP4URLResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMP4URLResponseBody(mp4url interface{}) *MP4URLResponseBody {
	this := MP4URLResponseBody{}
	this.Mp4url = mp4url
	return &this
}

// NewMP4URLResponseBodyWithDefaults instantiates a new MP4URLResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMP4URLResponseBodyWithDefaults() *MP4URLResponseBody {
	this := MP4URLResponseBody{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MP4URLResponseBody) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MP4URLResponseBody) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *MP4URLResponseBody) HasSchema() bool {
	if o != nil && IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given interface{} and assigns it to the Schema field.
func (o *MP4URLResponseBody) SetSchema(v interface{}) {
	o.Schema = v
}

// GetMp4url returns the Mp4url field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *MP4URLResponseBody) GetMp4url() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Mp4url
}

// GetMp4urlOk returns a tuple with the Mp4url field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MP4URLResponseBody) GetMp4urlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Mp4url) {
		return nil, false
	}
	return &o.Mp4url, true
}

// SetMp4url sets field value
func (o *MP4URLResponseBody) SetMp4url(v interface{}) {
	o.Mp4url = v
}

func (o MP4URLResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MP4URLResponseBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Schema != nil {
		toSerialize["$schema"] = o.Schema
	}
	if o.Mp4url != nil {
		toSerialize["mp4url"] = o.Mp4url
	}
	return toSerialize, nil
}

type NullableMP4URLResponseBody struct {
	value *MP4URLResponseBody
	isSet bool
}

func (v NullableMP4URLResponseBody) Get() *MP4URLResponseBody {
	return v.value
}

func (v *NullableMP4URLResponseBody) Set(val *MP4URLResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableMP4URLResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableMP4URLResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMP4URLResponseBody(val *MP4URLResponseBody) *NullableMP4URLResponseBody {
	return &NullableMP4URLResponseBody{value: val, isSet: true}
}

func (v NullableMP4URLResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMP4URLResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


