/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
)

// checks if the Package type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Package{}

// Package struct for Package
type Package struct {
	Archive Archive `json:"archive"`
	Dash *Location `json:"dash,omitempty"`
	Hls *Location `json:"hls,omitempty"`
	PackageId interface{} `json:"package_id"`
}

// NewPackage instantiates a new Package object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPackage(archive Archive, packageId interface{}) *Package {
	this := Package{}
	this.Archive = archive
	this.PackageId = packageId
	return &this
}

// NewPackageWithDefaults instantiates a new Package object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPackageWithDefaults() *Package {
	this := Package{}
	return &this
}

// GetArchive returns the Archive field value
func (o *Package) GetArchive() Archive {
	if o == nil {
		var ret Archive
		return ret
	}

	return o.Archive
}

// GetArchiveOk returns a tuple with the Archive field value
// and a boolean to check if the value has been set.
func (o *Package) GetArchiveOk() (*Archive, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archive, true
}

// SetArchive sets field value
func (o *Package) SetArchive(v Archive) {
	o.Archive = v
}

// GetDash returns the Dash field value if set, zero value otherwise.
func (o *Package) GetDash() Location {
	if o == nil || IsNil(o.Dash) {
		var ret Location
		return ret
	}
	return *o.Dash
}

// GetDashOk returns a tuple with the Dash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetDashOk() (*Location, bool) {
	if o == nil || IsNil(o.Dash) {
		return nil, false
	}
	return o.Dash, true
}

// HasDash returns a boolean if a field has been set.
func (o *Package) HasDash() bool {
	if o != nil && !IsNil(o.Dash) {
		return true
	}

	return false
}

// SetDash gets a reference to the given Location and assigns it to the Dash field.
func (o *Package) SetDash(v Location) {
	o.Dash = &v
}

// GetHls returns the Hls field value if set, zero value otherwise.
func (o *Package) GetHls() Location {
	if o == nil || IsNil(o.Hls) {
		var ret Location
		return ret
	}
	return *o.Hls
}

// GetHlsOk returns a tuple with the Hls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Package) GetHlsOk() (*Location, bool) {
	if o == nil || IsNil(o.Hls) {
		return nil, false
	}
	return o.Hls, true
}

// HasHls returns a boolean if a field has been set.
func (o *Package) HasHls() bool {
	if o != nil && !IsNil(o.Hls) {
		return true
	}

	return false
}

// SetHls gets a reference to the given Location and assigns it to the Hls field.
func (o *Package) SetHls(v Location) {
	o.Hls = &v
}

// GetPackageId returns the PackageId field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *Package) GetPackageId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.PackageId
}

// GetPackageIdOk returns a tuple with the PackageId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Package) GetPackageIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PackageId) {
		return nil, false
	}
	return &o.PackageId, true
}

// SetPackageId sets field value
func (o *Package) SetPackageId(v interface{}) {
	o.PackageId = v
}

func (o Package) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Package) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["archive"] = o.Archive
	if !IsNil(o.Dash) {
		toSerialize["dash"] = o.Dash
	}
	if !IsNil(o.Hls) {
		toSerialize["hls"] = o.Hls
	}
	if o.PackageId != nil {
		toSerialize["package_id"] = o.PackageId
	}
	return toSerialize, nil
}

type NullablePackage struct {
	value *Package
	isSet bool
}

func (v NullablePackage) Get() *Package {
	return v.value
}

func (v *NullablePackage) Set(val *Package) {
	v.value = val
	v.isSet = true
}

func (v NullablePackage) IsSet() bool {
	return v.isSet
}

func (v *NullablePackage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePackage(val *Package) *NullablePackage {
	return &NullablePackage{value: val, isSet: true}
}

func (v NullablePackage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePackage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


