/*
 * WBD Aventus Channels API
 *
 * API version: 0.0.0
 * Contact: live-control-plane-devs@wbd.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package isp

import (
	"encoding/json"
	"time"
)

// checks if the DeprecatedGetProgramResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeprecatedGetProgramResponse{}

// DeprecatedGetProgramResponse struct for DeprecatedGetProgramResponse
type DeprecatedGetProgramResponse struct {
	// An optional URL to a JSON Schema document describing this resource
	Schema             *string                                        `json:"$schema,omitempty" format:"uri" doc:"An optional URL to a JSON Schema document describing this resource"`
	ClearSegmentConfig DeprecatedGetProgramResponseClearSegmentConfig `json:"clear_segment_config"`
	// description of the program
	Description string `json:"description" doc:"description of the program"`
	// total number off files for the program
	FileCount int64 `json:"file_count" format:"int64" doc:"total number off files for the program"`
	// date last published
	LastPublished time.Time `json:"last_published" format:"date-time" doc:"date last published"`
	// id for the program
	Progid string `json:"progid" doc:"id for the program"`
	// clip id
	PubClipId int64 `json:"pub_clip_id" format:"int64" doc:"clip id"`
	// vod id
	PubVodId int64 `json:"pub_vod_id" format:"int64" doc:"vod id"`
	// number of days to retain
	RetentionDays int64 `json:"retention_days" format:"int64" doc:"number of days to retain"`
	// total bytes in the program
	TotalBytes int64 `json:"total_bytes" format:"int64" doc:"total bytes in the program"`
}

// NewDeprecatedGetProgramResponse instantiates a new DeprecatedGetProgramResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeprecatedGetProgramResponse(clearSegmentConfig DeprecatedGetProgramResponseClearSegmentConfig, description string, fileCount int64, lastPublished time.Time, progid string, pubClipId int64, pubVodId int64, retentionDays int64, totalBytes int64) *DeprecatedGetProgramResponse {
	this := DeprecatedGetProgramResponse{}
	this.ClearSegmentConfig = clearSegmentConfig
	this.Description = description
	this.FileCount = fileCount
	this.LastPublished = lastPublished
	this.Progid = progid
	this.PubClipId = pubClipId
	this.PubVodId = pubVodId
	this.RetentionDays = retentionDays
	this.TotalBytes = totalBytes
	return &this
}

// NewDeprecatedGetProgramResponseWithDefaults instantiates a new DeprecatedGetProgramResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeprecatedGetProgramResponseWithDefaults() *DeprecatedGetProgramResponse {
	this := DeprecatedGetProgramResponse{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *DeprecatedGetProgramResponse) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeprecatedGetProgramResponse) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *DeprecatedGetProgramResponse) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *DeprecatedGetProgramResponse) SetSchema(v string) {
	o.Schema = &v
}

// GetClearSegmentConfig returns the ClearSegmentConfig field value
func (o *DeprecatedGetProgramResponse) GetClearSegmentConfig() DeprecatedGetProgramResponseClearSegmentConfig {
	if o == nil {
		var ret DeprecatedGetProgramResponseClearSegmentConfig
		return ret
	}

	return o.ClearSegmentConfig
}

// GetClearSegmentConfigOk returns a tuple with the ClearSegmentConfig field value
// and a boolean to check if the value has been set.
func (o *DeprecatedGetProgramResponse) GetClearSegmentConfigOk() (*DeprecatedGetProgramResponseClearSegmentConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClearSegmentConfig, true
}

// SetClearSegmentConfig sets field value
func (o *DeprecatedGetProgramResponse) SetClearSegmentConfig(v DeprecatedGetProgramResponseClearSegmentConfig) {
	o.ClearSegmentConfig = v
}

// GetDescription returns the Description field value
func (o *DeprecatedGetProgramResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *DeprecatedGetProgramResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *DeprecatedGetProgramResponse) SetDescription(v string) {
	o.Description = v
}

// GetFileCount returns the FileCount field value
func (o *DeprecatedGetProgramResponse) GetFileCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FileCount
}

// GetFileCountOk returns a tuple with the FileCount field value
// and a boolean to check if the value has been set.
func (o *DeprecatedGetProgramResponse) GetFileCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileCount, true
}

// SetFileCount sets field value
func (o *DeprecatedGetProgramResponse) SetFileCount(v int64) {
	o.FileCount = v
}

// GetLastPublished returns the LastPublished field value
func (o *DeprecatedGetProgramResponse) GetLastPublished() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastPublished
}

// GetLastPublishedOk returns a tuple with the LastPublished field value
// and a boolean to check if the value has been set.
func (o *DeprecatedGetProgramResponse) GetLastPublishedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastPublished, true
}

// SetLastPublished sets field value
func (o *DeprecatedGetProgramResponse) SetLastPublished(v time.Time) {
	o.LastPublished = v
}

// GetProgid returns the Progid field value
func (o *DeprecatedGetProgramResponse) GetProgid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Progid
}

// GetProgidOk returns a tuple with the Progid field value
// and a boolean to check if the value has been set.
func (o *DeprecatedGetProgramResponse) GetProgidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Progid, true
}

// SetProgid sets field value
func (o *DeprecatedGetProgramResponse) SetProgid(v string) {
	o.Progid = v
}

// GetPubClipId returns the PubClipId field value
func (o *DeprecatedGetProgramResponse) GetPubClipId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PubClipId
}

// GetPubClipIdOk returns a tuple with the PubClipId field value
// and a boolean to check if the value has been set.
func (o *DeprecatedGetProgramResponse) GetPubClipIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PubClipId, true
}

// SetPubClipId sets field value
func (o *DeprecatedGetProgramResponse) SetPubClipId(v int64) {
	o.PubClipId = v
}

// GetPubVodId returns the PubVodId field value
func (o *DeprecatedGetProgramResponse) GetPubVodId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.PubVodId
}

// GetPubVodIdOk returns a tuple with the PubVodId field value
// and a boolean to check if the value has been set.
func (o *DeprecatedGetProgramResponse) GetPubVodIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PubVodId, true
}

// SetPubVodId sets field value
func (o *DeprecatedGetProgramResponse) SetPubVodId(v int64) {
	o.PubVodId = v
}

// GetRetentionDays returns the RetentionDays field value
func (o *DeprecatedGetProgramResponse) GetRetentionDays() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RetentionDays
}

// GetRetentionDaysOk returns a tuple with the RetentionDays field value
// and a boolean to check if the value has been set.
func (o *DeprecatedGetProgramResponse) GetRetentionDaysOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RetentionDays, true
}

// SetRetentionDays sets field value
func (o *DeprecatedGetProgramResponse) SetRetentionDays(v int64) {
	o.RetentionDays = v
}

// GetTotalBytes returns the TotalBytes field value
func (o *DeprecatedGetProgramResponse) GetTotalBytes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.TotalBytes
}

// GetTotalBytesOk returns a tuple with the TotalBytes field value
// and a boolean to check if the value has been set.
func (o *DeprecatedGetProgramResponse) GetTotalBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalBytes, true
}

// SetTotalBytes sets field value
func (o *DeprecatedGetProgramResponse) SetTotalBytes(v int64) {
	o.TotalBytes = v
}

func (o DeprecatedGetProgramResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeprecatedGetProgramResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["clear_segment_config"] = o.ClearSegmentConfig
	toSerialize["description"] = o.Description
	toSerialize["file_count"] = o.FileCount
	toSerialize["last_published"] = o.LastPublished
	toSerialize["progid"] = o.Progid
	toSerialize["pub_clip_id"] = o.PubClipId
	toSerialize["pub_vod_id"] = o.PubVodId
	toSerialize["retention_days"] = o.RetentionDays
	toSerialize["total_bytes"] = o.TotalBytes
	return toSerialize, nil
}

type NullableDeprecatedGetProgramResponse struct {
	value *DeprecatedGetProgramResponse
	isSet bool
}

func (v NullableDeprecatedGetProgramResponse) Get() *DeprecatedGetProgramResponse {
	return v.value
}

func (v *NullableDeprecatedGetProgramResponse) Set(val *DeprecatedGetProgramResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeprecatedGetProgramResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeprecatedGetProgramResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeprecatedGetProgramResponse(val *DeprecatedGetProgramResponse) *NullableDeprecatedGetProgramResponse {
	return &NullableDeprecatedGetProgramResponse{value: val, isSet: true}
}

func (v NullableDeprecatedGetProgramResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeprecatedGetProgramResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
